Repository memgraph/documentation, pull requests merged in 2023-12, with the labels that each got.

#353 Fix typos
  pages/custom-query-modules.mdx
  pages/fundamentals/transactions.mdx
  pages/getting-started/install-memgraph/docker-compose.md
Labels: status: ready

#345 [memgraph-2-13 < ] schema.assert
  pages/fundamentals/constraints.mdx
  pages/fundamentals/indexes.mdx
  pages/querying/functions.mdx
  pages/querying/performance-optimization.md
  pages/querying/schema.mdx
Labels: status: draft

#361 [memgraph-v2-13 < 361] Document query module behavior in analytical mode
  pages/custom-query-modules/c/c-api.mdx
  pages/custom-query-modules/cpp/cpp-api.md
  pages/custom-query-modules/python/python-api.mdx
  pages/fundamentals/storage-memory-usage.mdx
Labels: status: ready

#365 [memgraph-v2-13 < 365] Add accumulated path and weight description
  pages/advanced-algorithms/built-in-graph-algorithms.mdx
Labels: status: ready

#358 Add Lab v2.10 release notes
  pages/release-notes.mdx
Labels: status: ship it

#342 [main<] Memgraph 2.13 and MAGE 1.13
  pages/advanced-algorithms/available-algorithms/text.mdx
  pages/advanced-algorithms/built-in-graph-algorithms.mdx
  pages/configuration/configuration-settings.mdx
  pages/custom-query-modules/cpp/cpp-api.md
  pages/fundamentals/constraints.mdx
  pages/fundamentals/indexes.mdx
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/querying/functions.mdx
  pages/querying/performance-optimization.md
  pages/querying/schema.mdx
  pages/release-notes.mdx
Labels: status: ship it

#339 [main<] Telemetry
  pages/fundamentals/telemetry.mdx
Labels: status: draft

#87 [main < 54-implement-algolia-search] Add Algolia search
  components/docsearch.js
  pages/_document.js
  styles/globals.css
  theme.config.tsx
Labels: status: ready

#376 [main < ] Batch of improved query modules
  pages/advanced-algorithms/available-algorithms/refactor.mdx
  pages/advanced-algorithms/available-algorithms/set_cover.mdx
  pages/advanced-algorithms/available-algorithms/temporal.mdx
  pages/advanced-algorithms/available-algorithms/text.mdx
  pages/advanced-algorithms/available-algorithms/tsp.mdx
  pages/advanced-algorithms/available-algorithms/union_find.mdx
  pages/advanced-algorithms/available-algorithms/util_module.mdx
  pages/advanced-algorithms/available-algorithms/uuid_generator.mdx
  pages/advanced-algorithms/available-algorithms/vrp.mdx
  pages/advanced-algorithms/available-algorithms/weakly_connected_components.mdx
  pages/advanced-algorithms/available-algorithms/xml_module.mdx
Labels: status: draft

#383 Fix configuration parameters
  pages/configuration/auth-module.mdx
  pages/configuration/configuration-settings.mdx
  pages/help-center/errors/auth.mdx
Labels: status: ship it

#219 [main < ] Improve C++ query module developer experience
  pages/custom-query-modules.mdx
  pages/custom-query-modules/cpp.mdx
  pages/custom-query-modules/cpp/cpp-example.mdx
  public/sitemap.xml
Labels: status: ready

#387 Fix typo
  pages/advanced-algorithms/install-mage.mdx
Labels: status: ship it

#388 Add section
  pages/getting-started/first-steps-with-docker.mdx
Labels: status: ship it

#389 Update example
  pages/querying.mdx
Labels: status: ship it

#390 Add new callout
  pages/data-visualization/user-manual.mdx
Labels: status: ship it

#391 Add example
  pages/querying/expressions.mdx
Labels: status: ship it
