Repository memgraph/documentation, pull requests merged in 2023-10, with the labels that each got.

#236 [main < ] Fix typo "develooped"
  pages/custom-query-modules.mdx
Labels: priority: low (improvements), status: ready

#220 [memgraph-2.12 < Storage mode flag ] Add storage mode flag for starting Memgraph
  pages/configuration/configuration-settings.mdx
  pages/fundamentals/storage-memory-usage.mdx
Labels: status: ready

#218 [main<] Updating and unifying query module docs
  pages/advanced-algorithms/available-algorithms/betweenness_centrality.mdx
  pages/advanced-algorithms/available-algorithms/betweenness_centrality_online.mdx
  pages/advanced-algorithms/available-algorithms/biconnected_components.mdx
  pages/advanced-algorithms/available-algorithms/bipartite_matching.mdx
  pages/advanced-algorithms/available-algorithms/bridges.mdx
  pages/advanced-algorithms/available-algorithms/community_detection.mdx
  pages/advanced-algorithms/available-algorithms/community_detection_online.mdx
  pages/advanced-algorithms/available-algorithms/conditional_execution.mdx
  pages/advanced-algorithms/available-algorithms/create.mdx
  pages/advanced-algorithms/available-algorithms/cugraph.mdx
  pages/advanced-algorithms/available-algorithms/cycles.mdx
  pages/advanced-algorithms/available-algorithms/date.mdx
  pages/advanced-algorithms/available-algorithms/degree_centrality.mdx
  pages/fundamentals/storage-memory-usage.mdx
Labels: status: draft

#221 [main <] Improve fundamental pages
  pages/fundamentals/constraints.md
  pages/fundamentals/data-types.mdx
  pages/fundamentals/graph-modeling.md
  pages/fundamentals/telemetry.mdx
  public/pages/fundamentals/graph-modeling/graph-modeling-describe-domain.png
  public/pages/fundamentals/graph-modeling/graph-modeling-directed-graph.png
  public/pages/fundamentals/graph-modeling/graph-modeling-labels.png
  public/pages/fundamentals/graph-modeling/graph-modeling-mapping-relationships.png
  public/pages/fundamentals/graph-modeling/graph-modeling-nodes.png
  public/pages/fundamentals/graph-modeling/graph-modeling-properties.png
  public/pages/fundamentals/graph-modeling/graph-modeling-property-or-relationship.png
  public/pages/fundamentals/graph-modeling/graph-modeling-relationships.png
  public/pages/fundamentals/graph-modeling/graph-modeling-storing-properties.png
  public/pages/fundamentals/graph-modeling/graph-modeling-un-directed-graph.png
  public/pages/fundamentals/graph-modeling/graph-modeling-undirected-graph.png
  public/pages/fundamentals/graph-modeling/graph-modeling-weighted-graph.png
Labels: status: draft

#239 [main < ] Batch 3 of query modules
  components/icons/GitHub.js
  pages/advanced-algorithms/available-algorithms/distance_calculator.mdx
  pages/advanced-algorithms/available-algorithms/elasticsearch_synchronization.mdx
  pages/advanced-algorithms/available-algorithms/export_util.mdx
  pages/advanced-algorithms/available-algorithms/graph_analyzer.mdx
  pages/advanced-algorithms/available-algorithms/graph_coloring.mdx
  pages/advanced-algorithms/available-algorithms/graph_util.mdx
  public/pages/advanced-algorithms/available-algorithms/distance_calculator/distance-calculator-2.png
Labels: status: draft

#249 [main<] Improvements of QM - part 4
  pages/advanced-algorithms/available-algorithms/date.mdx
  pages/advanced-algorithms/available-algorithms/elasticsearch_synchronization.mdx
  pages/advanced-algorithms/available-algorithms/export_util.mdx
  pages/advanced-algorithms/available-algorithms/gnn_node_classification.mdx
  pages/advanced-algorithms/available-algorithms/graph_util.mdx
  pages/advanced-algorithms/available-algorithms/igraphalg.mdx
  pages/advanced-algorithms/available-algorithms/import_util.mdx
  pages/advanced-algorithms/available-algorithms/json_util.mdx
  pages/advanced-algorithms/available-algorithms/katz_centrality.mdx
  pages/advanced-algorithms/available-algorithms/katz_centrality_online.mdx
  pages/advanced-algorithms/available-algorithms/kmeans_clustering.mdx
  pages/advanced-algorithms/available-algorithms/label.mdx
  pages/advanced-algorithms/available-algorithms/llm_util.mdx
  pages/advanced-algorithms/available-algorithms/map.mdx
  pages/advanced-algorithms/available-algorithms/max_flow.mdx
  pages/advanced-algorithms/available-algorithms/meta.mdx
  pages/advanced-algorithms/available-algorithms/meta_util.mdx
  pages/advanced-algorithms/available-algorithms/migrate.mdx
  pages/advanced-algorithms/available-algorithms/neighbors.mdx
  pages/advanced-algorithms/available-algorithms/node.mdx
  pages/advanced-algorithms/available-algorithms/node2vec.mdx
  pages/advanced-algorithms/available-algorithms/node2vec_online.mdx
  pages/advanced-algorithms/available-algorithms/node_similarity.mdx
  pages/advanced-algorithms/available-algorithms/nodes.mdx
  pages/advanced-algorithms/available-algorithms/tgn.mdx
  pages/advanced-algorithms/available-algorithms/util_module.mdx
Labels: status: draft

#257 [main< ] Memgraph Lab 2.8.4 release notes
  pages/release-notes.mdx
Labels: status: ready

#258 [memgraph-2-12 < ] Update Storage mode with new data format
  pages/fundamentals/storage-memory-usage.mdx
Labels: status: ready

#259 Update README.md
  README.md
Labels: status: ready

#255 [main < ] Add basic graphql docs
  components/icons/Graphql.js
  pages/client-libraries.mdx
  pages/client-libraries/_meta.json
  pages/client-libraries/go.mdx
  pages/client-libraries/graphql.mdx
  pages/client-libraries/java.mdx
  pages/client-libraries/python.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/getting-started.mdx
  pages/index.mdx
Labels: status: ready

#264 [memgraph-2-12 < E-MAGE-node] Write docs for node-in-out-degree
  pages/advanced-algorithms/available-algorithms/node.mdx
Labels: status: ready

#268 [memgraph-v2-11 < 268] Document detailed filter info in query plans
  pages/fundamentals/indexes.mdx
  pages/querying/clauses/profile.md
  pages/querying/performance-optimization.md
Labels: status: ready

#270 [memgraph-v2-11 < 270] Document the new HashJoin operator
  pages/configuration/monitoring-server.mdx
  pages/querying/performance-optimization.md
Labels: status: ready, release: mg-v2.12.0

#271 [memgraph-2-12 <] Write docs for refactor.rename_type_property
  pages/advanced-algorithms/available-algorithms/refactor.mdx
  public/pages/advanced-algorithms/available-algorithms/refactor/rename_prop_after.png
  public/pages/advanced-algorithms/available-algorithms/refactor/rename_prop_before.png
Labels: status: ready

#272 [memgraph-v2-11 < 272] Add index hinting documentation
  pages/fundamentals/indexes.mdx
  pages/querying/performance-optimization.md
Labels: status: ready, release: mg-v2.12.0

#273 [memgraph-2.12 < api-rename-type] Docs for renaming edge type in API
  pages/custom-query-modules/c/c-api.mdx
  pages/custom-query-modules/cpp/cpp-api.md
Labels: status: ready, release: mg-v2.12.0

#278 Clarify the complexity of online BC
  pages/advanced-algorithms/available-algorithms/betweenness_centrality_online.mdx
Labels: priority: high (error), status: ready

#274 [memgraph-2.12 < E-mage-path-ivan] Add docs for path
  pages/advanced-algorithms/available-algorithms/path.mdx
Labels: status: ready, release: mg-v2.12.0

#279 [memgraph-2-12<] Update replication docs
  pages/configuration/replication.mdx
Labels: status: ready, release: mg-v2.12.0

#282 Cartesian product
  README.md
  components/icons/Graphql.js
  next.config.js
  pages/advanced-algorithms.mdx
  pages/advanced-algorithms/available-algorithms/betweenness_centrality_online.mdx
  pages/advanced-algorithms/run-algorithms.mdx
  pages/client-libraries.mdx
  pages/client-libraries/_meta.json
  pages/client-libraries/go.mdx
  pages/client-libraries/graphql.mdx
  pages/client-libraries/java.mdx
  pages/client-libraries/python.mdx
  pages/configuration/configuration-settings.mdx
  pages/configuration/monitoring-server.mdx
  pages/configuration/replication.mdx
  pages/data-visualization/install-and-connect.mdx
  pages/fundamentals/indexes.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/getting-started.mdx
  pages/getting-started/first-steps-with-memgraph.mdx
  pages/index.mdx
  pages/querying/clauses/profile.md
  pages/querying/performance-optimization.md
  public/sitemap.xml
Labels: status: ready, release: mg-v2.12.0

#277 [memgraph-2-12] Write docs for merge module
  pages/advanced-algorithms/available-algorithms.md
  pages/advanced-algorithms/available-algorithms/_meta.json
  pages/advanced-algorithms/available-algorithms/merge.mdx
Labels: status: ship it, release: mg-v2.12.0

#284 [memgraph-2.12 < T] Improve global and query memory limit
  pages/fundamentals/storage-memory-usage.mdx
Labels: release: mg-v2.12.0

#285 Add function docs
  pages/querying/functions.mdx
Labels: release: mg-v2.12.0

#283 [memgraph-2-12 < ] Write docs for algo query module
  pages/advanced-algorithms/available-algorithms.md
  pages/advanced-algorithms/available-algorithms/_meta.json
  pages/advanced-algorithms/available-algorithms/algo.mdx
  public/pages/advanced-algorithms/available-algorithms/algo/a_star_graph.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result1.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result2.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result3.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result4.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result5.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result6.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result7.png
  public/pages/advanced-algorithms/available-algorithms/algo/cover_graph.png
  public/pages/advanced-algorithms/available-algorithms/algo/cover_result.png
  public/pages/advanced-algorithms/available-algorithms/algo/simplepaths_graph.png
Labels: status: ready, release: mg-v2.12.0

#288 [memgraph-2.12 < E-add-refactor]
  pages/advanced-algorithms/available-algorithms/refactor.mdx
  public/pages/advanced-algorithms/available-algorithms/refactor/extract_node_after.png
Labels: status: ready, release: mg-v2.12.0

#261 Improve php and add fixes to python guide
  pages/client-libraries/php.mdx
  pages/client-libraries/python.mdx
  public/pages/client-libraries/php/php-visualization.png
  public/pages/client-libraries/python/python-quick-start.png
Labels: status: ready
