Repository memgraph/documentation, pull requests merged in 2023-09, with the labels that each got.

#116 [main < github-links] Add GitHub links
  theme.config.tsx
Labels: status: ship it

#42 Add Golang client getting started
  pages/client-libraries/go.mdx
  public/pages/client-libraries/go/go-quick-start.png
Labels: status: ship it

#88 [main<] Fixes I come accross
  pages/advanced-algorithms/available-algorithms/collections.mdx
  pages/custom-query-modules/cpp/cpp-api.md
  pages/getting-started/install-memgraph.mdx
Labels: status: draft

#91 Add JAVA getting started guide
  pages/client-libraries/java.mdx
  public/pages/client-libraries/java/java-quick-start.png
Labels: status: ship it

#55 add Python getting started guide
  pages/client-libraries/python.mdx
  public/pages/client-libraries/new-python/python-quick-start.png
Labels: status: ready

#141 Add CODEOWNERS to docs
  .github/CODEOWNERS
Labels: status: ready

#30 [main <] custom-procedures
  pages/custom-query-modules.mdx
  pages/custom-query-modules/c.mdx
  pages/custom-query-modules/contributing.mdx
  pages/custom-query-modules/cpp.mdx
  pages/custom-query-modules/manage-query-modules.mdx
  pages/custom-query-modules/python.mdx
Labels: status: draft

#150 [main < 149-implement-dark] Implement dark mode
  components/Footer.js
  package.json
  pages/_app.tsx
  public/external-link.svg
  public/memgraph-logo-background.png
  public/memgraph-logo-footer-dark.svg
  public/sitemap.xml
  styles/globals.css
  tailwind.config.js
  theme.config.tsx
Labels: status: ship it

#142 [main < 139-update-first...] Update page First steps with Memgraph
  pages/fundamentals/_meta.json
  pages/getting-started/first-steps-with-memgraph.mdx
  public/pages/getting-started/first-steps/connect-to-memgraph-lab.png
  public/pages/getting-started/first-steps/memgraph-lab-cypher-editor.png
  public/pages/getting-started/first-steps/memgraph-lab-dashboard.png
  public/pages/getting-started/first-steps/memgraph-lab-dataset-import.png
  public/pages/getting-started/first-steps/memgraph-lab-datasets.png
  public/pages/getting-started/first-steps/memgraph-lab-first-cypher-query.png
  public/pages/getting-started/first-steps/memgraph-lab-graph-results.png
  public/pages/getting-started/first-steps/memgraph-lab-map-style-final.png
  public/pages/getting-started/first-steps/memgraph-lab-map-style.png
  public/pages/getting-started/first-steps/memgraph-lab-style-editor.png
  public/pages/getting-started/first-steps/pagerank-results.png
  public/pages/getting-started/first-steps/query-modules.png
  public/pages/getting-started/first-steps/yt-video-preview.png
Labels: status: ready

#144 Update the description of SHOW INDEX INFO
  .github/CODEOWNERS
  README.md
  pages/_app.tsx
  pages/client-libraries/java.mdx
  pages/client-libraries/python.mdx
  pages/client-libraries/rust.md
  pages/client-libraries/rust.mdx
  pages/fundamentals/indexes.mdx
  pages/getting-started.mdx
  pages/getting-started/install-memgraph.mdx
  public/pages/client-libraries/java/java-quick-start.png
  public/pages/client-libraries/new-python/python-quick-start.png
  public/pages/client-libraries/rust/rust-quick-start.png
  public/sitemap-0.xml
  public/sitemap.xml
  styles/globals.css
  theme.config.tsx
Labels: status: ready, memgraph-2.11.

#160 [memgraph-v2-11 < 160] Add bulk property-setting to query module APIs docs
  pages/custom-query-modules/c/c-api.mdx
  pages/custom-query-modules/cpp/cpp-api.md
  pages/custom-query-modules/python/python-api.mdx
Labels: status: ship it, memgraph-2.11.

#159 [main < 51-remove-references...] Remove references to non-existent pages.
  pages/configuration/exposing-system-metrics.md
  pages/custom-query-modules/python/understanding-music-with-modules.mdx
  pages/getting-started/install-memgraph/docker.mdx
  pages/getting-started/install-memgraph/rpm-package.mdx
  pages/getting-started/install-memgraph/wsl.mdx
  pages/help-center/faq.md
  pages/querying/exploring-datasets/analyzing-ted-talks.md
  pages/querying/exploring-datasets/backpacking-through-europe.md
  pages/querying/exploring-datasets/exploring-the-european-road-network.md
  pages/querying/exploring-datasets/football-transfers.md
  pages/querying/exploring-datasets/got-deaths.md
  pages/querying/exploring-datasets/graphing-the-premier-league.md
  pages/querying/exploring-datasets/marvel-universe.md
  pages/querying/exploring-datasets/movie-recommendation.md
Labels: status: ready

#158 Add docs for edge import mode.
  pages/data-migration/csv.mdx
  pages/data-migration/cypherl.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/release-notes.mdx
Labels: status: ready, memgraph-2.11.

#165 [main < fix-blue-links] Update broken links
  pages/advanced-algorithms/available-algorithms/conditional_execution.mdx
  pages/advanced-algorithms/available-algorithms/cugraph.mdx
  pages/advanced-algorithms/available-algorithms/degree_centrality.mdx
  pages/advanced-algorithms/available-algorithms/distance_calculator.mdx
  pages/advanced-algorithms/available-algorithms/graph_util.mdx
  pages/advanced-algorithms/available-algorithms/periodic.mdx
  pages/custom-query-modules/python/understanding-music-with-modules.mdx
  pages/getting-started/install-memgraph/wsl.mdx
  pages/querying/exploring-datasets/football-transfers.md
Labels: status: draft

#157 [main<] Documentation for Memgraph v2.11
  pages/advanced-algorithms/available-algorithms.md
  pages/advanced-algorithms/available-algorithms/_meta.json
  pages/advanced-algorithms/available-algorithms/collections.mdx
  pages/advanced-algorithms/available-algorithms/convert.mdx
  pages/advanced-algorithms/available-algorithms/create.mdx
  pages/advanced-algorithms/available-algorithms/export_util.mdx
  pages/advanced-algorithms/available-algorithms/import_util.mdx
  pages/advanced-algorithms/available-algorithms/meta.mdx
  pages/advanced-algorithms/available-algorithms/neighbors.mdx
  pages/advanced-algorithms/available-algorithms/node.mdx
  pages/advanced-algorithms/available-algorithms/nodes.mdx
  pages/advanced-algorithms/available-algorithms/path.mdx
  pages/advanced-algorithms/available-algorithms/refactor.mdx
  pages/advanced-algorithms/available-algorithms/schema.mdx
  pages/advanced-algorithms/available-algorithms/temporal.mdx
  pages/advanced-algorithms/available-algorithms/util_module.mdx
  pages/advanced-algorithms/available-algorithms/xml_module.mdx
  pages/configuration/configuration-settings.mdx
  pages/custom-query-modules/c/c-api.mdx
  pages/custom-query-modules/cpp/cpp-api.md
  pages/custom-query-modules/python/python-api.mdx
  pages/data-migration/csv.mdx
  pages/data-migration/cypherl.mdx
  pages/fundamentals/indexes.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/querying/performance-optimization.md
  pages/release-notes.mdx
  public/pages/advanced-algorithms/available-algorithms/export_util/csv_graph.png
  public/pages/advanced-algorithms/available-algorithms/import_util/import_util_graphml.png
  public/pages/advanced-algorithms/available-algorithms/neighbors/neighbors.png
  public/pages/advanced-algorithms/available-algorithms/nodes/graph_after.png
  public/pages/advanced-algorithms/available-algorithms/nodes/graph_before.png
  public/pages/advanced-algorithms/available-algorithms/path/graph.png
  public/pages/advanced-algorithms/available-algorithms/path/graph_usage1.png
  public/pages/advanced-algorithms/available-algorithms/path/graph_usage2.png
  public/pages/advanced-algorithms/available-algorithms/path/graph_usage3.png
  public/pages/advanced-algorithms/available-algorithms/path/subgraphall1.png
  public/pages/advanced-algorithms/available-algorithms/path/subgraphall2.png
  public/pages/advanced-algorithms/available-algorithms/path/subgraphnodes1.png
  public/pages/advanced-algorithms/available-algorithms/path/subgraphnodes2.png
  public/pages/advanced-algorithms/available-algorithms/refactor/categorize1.png
  public/pages/advanced-algorithms/available-algorithms/refactor/categorize2.png
  public/pages/advanced-algorithms/available-algorithms/refactor/clonenodes1.png
  public/pages/advanced-algorithms/available-algorithms/refactor/clonenodes2.png
  public/pages/advanced-algorithms/available-algorithms/refactor/clonesubgraph1.png
  public/pages/advanced-algorithms/available-algorithms/refactor/clonesubgraph2.png
  public/pages/advanced-algorithms/available-algorithms/refactor/clonesubgraphpath1.png
  public/pages/advanced-algorithms/available-algorithms/refactor/clonesubgraphpath2.png
  public/pages/advanced-algorithms/available-algorithms/refactor/graph_after.png
  public/pages/advanced-algorithms/available-algorithms/refactor/graph_before.png
  public/pages/advanced-algorithms/available-algorithms/refactor/rel_after.png
  public/pages/advanced-algorithms/available-algorithms/refactor/rel_before.png
Labels: status: ready, memgraph-2.11.

#173 [main < ] Fix mistake in docs about cosine similarity
  pages/advanced-algorithms/available-algorithms/node_similarity.mdx
Labels: status: ready

#172 [main < ] Modify C++ API description
  pages/custom-query-modules/cpp/cpp-api.md
  pages/custom-query-modules/cpp/cpp-example.mdx
Labels: status: ready

#179 [main < 404-redirects...]
  next.config.js
  public/sitemap.xml
Labels: status: ship it

#190 [main<] Small stuff
  pages/advanced-algorithms/available-algorithms/_meta.json
  pages/getting-started/first-steps-with-memgraph.mdx
Labels: status: ship it

#189 [main<] Fix link typo
  pages/client-libraries/go.mdx
Labels: status: ship it

#95 [main<] JavaScript client library guide
  pages/client-libraries/javascript.mdx
  public/pages/client-libraries/javascript/javascript-quick-start.png
Labels: status: ready

#185 [main < c-api-docs] Add missing C-API docs
  pages/custom-query-modules/c/c-api.mdx
Labels: status: ready

#208 [main< ] Improve storage memory
  components/icons/CSharp.js
  components/icons/Cpp.js
  components/icons/Go.js
  components/icons/Haskell.js
  components/icons/Java.js
  components/icons/JavaScript.js
  components/icons/NodeJS.js
  components/icons/PHP.js
  components/icons/Python.js
  components/icons/Ruby.js
  components/icons/Rust.js
  next.config.js
  pages/advanced-algorithms/available-algorithms/gnn_link_prediction.mdx
  pages/client-libraries.mdx
  pages/configuration.md
  pages/configuration/_meta.json
  pages/configuration/auth-module.md
  pages/configuration/auth-module.mdx
  pages/configuration/configuration-settings.mdx
  pages/configuration/data-durability-and-backup.mdx
  pages/configuration/enabling-memgraph-enterprise.mdx
  pages/configuration/exposing-system-metrics.md
  pages/configuration/ldap-security.mdx
  pages/configuration/logs.mdx
  pages/configuration/monitoring-server.mdx
  pages/configuration/multi-tenancy.md
  pages/configuration/security.mdx
  pages/fundamentals/indexes.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/getting-started.mdx
  pages/getting-started/install-memgraph.mdx
  pages/index.mdx
  pages/querying/performance-optimization.md
  pages/release-notes.mdx
  public/sitemap.xml
Labels: status: draft

#201 [mage-1-11-1 < E-graphQL] Update docs after refactor for GraphQL and fix some mistakes
  pages/advanced-algorithms/available-algorithms.md
  pages/advanced-algorithms/available-algorithms/collections.mdx
  pages/advanced-algorithms/available-algorithms/convert.mdx
  pages/advanced-algorithms/available-algorithms/create.mdx
  pages/advanced-algorithms/available-algorithms/date.mdx
  pages/advanced-algorithms/available-algorithms/label.mdx
  pages/advanced-algorithms/available-algorithms/map.mdx
  pages/advanced-algorithms/available-algorithms/meta.mdx
  pages/advanced-algorithms/available-algorithms/neighbors.mdx
  pages/advanced-algorithms/available-algorithms/node.mdx
  pages/advanced-algorithms/available-algorithms/nodes.mdx
  pages/advanced-algorithms/available-algorithms/refactor.mdx
  pages/advanced-algorithms/available-algorithms/schema.mdx
  pages/advanced-algorithms/available-algorithms/temporal.mdx
  pages/advanced-algorithms/available-algorithms/text.mdx
  pages/advanced-algorithms/available-algorithms/util_module.mdx
Labels: status: ship it

#225 [main< ] Docker images - differences
  components/icons/Java.js
  components/icons/PHP.js
  components/icons/Ruby.js
  components/icons/Rust.js
  pages/getting-started.mdx
  pages/getting-started/install-memgraph.mdx
  pages/getting-started/install-memgraph/docker.mdx
Labels: status: ship it

#230 Docker images
  pages/getting-started.mdx
  pages/getting-started/install-memgraph.mdx
  pages/getting-started/install-memgraph/docker.mdx
Labels: status: ship it

#231 [main < ] LOAD CSV improvements
  pages/data-migration/csv.mdx
Labels: status: ready

#214 [main < 204-expand-getting-started...] Add new page Getting started with Docker
  next.config.js
  pages/getting-started/_meta.json
  pages/getting-started/first-steps-with-docker.mdx
  pages/getting-started/install-memgraph/docker.mdx
  public/pages/getting-started/first-steps-with-docker/first-steps-with-docker-desktop.png
  public/pages/getting-started/first-steps-with-docker/first-steps-with-docker-install.png
  public/pages/getting-started/first-steps-with-docker/first-steps-with-docker-settings.png
  public/pages/getting-started/first-steps-with-docker/first-steps-with-docker-terms.png
  public/sitemap.xml
Labels: status: ship it

#184 [memgraph-2-12 < api-path-pop] Add docs for path pop in API
  pages/custom-query-modules/c/c-api.mdx
  pages/custom-query-modules/cpp/cpp-api.md
  pages/custom-query-modules/python/mock-python-api.md
  pages/custom-query-modules/python/python-api.mdx
Labels: status: ship it

#226 Add Node.js guide
  pages/client-libraries/nodejs.md
  pages/client-libraries/nodejs.mdx
  public/pages/client-libraries/nodejs/nodejs-quick-start.png
Labels: status: ship it

#213 [main < mage-1-11-1] Release MAGE v1.11.1
  pages/advanced-algorithms/available-algorithms.md
  pages/advanced-algorithms/available-algorithms/collections.mdx
  pages/advanced-algorithms/available-algorithms/convert.mdx
  pages/advanced-algorithms/available-algorithms/create.mdx
  pages/advanced-algorithms/available-algorithms/date.mdx
  pages/advanced-algorithms/available-algorithms/label.mdx
  pages/advanced-algorithms/available-algorithms/map.mdx
  pages/advanced-algorithms/available-algorithms/meta.mdx
  pages/advanced-algorithms/available-algorithms/neighbors.mdx
  pages/advanced-algorithms/available-algorithms/node.mdx
  pages/advanced-algorithms/available-algorithms/nodes.mdx
  pages/advanced-algorithms/available-algorithms/refactor.mdx
  pages/advanced-algorithms/available-algorithms/schema.mdx
  pages/advanced-algorithms/available-algorithms/temporal.mdx
  pages/advanced-algorithms/available-algorithms/text.mdx
  pages/advanced-algorithms/available-algorithms/util_module.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/release-notes.mdx
Labels: status: ship it

#234 Update docker-compose file
  pages/getting-started/install-memgraph/docker-compose.md
Labels: status: ready
