Repository memgraph/documentation, pull requests merged in 2023-11, with the labels that each got.

#232 [main < memgraph-2-12] Docs for Memgraph 2.12
  next.config.js
  pages/advanced-algorithms/available-algorithms.md
  pages/advanced-algorithms/available-algorithms/_meta.json
  pages/advanced-algorithms/available-algorithms/algo.mdx
  pages/advanced-algorithms/available-algorithms/convert.mdx
  pages/advanced-algorithms/available-algorithms/merge.mdx
  pages/advanced-algorithms/available-algorithms/node.mdx
  pages/advanced-algorithms/available-algorithms/path.mdx
  pages/advanced-algorithms/available-algorithms/refactor.mdx
  pages/advanced-algorithms/available-algorithms/schema.mdx
  pages/client-libraries/go.mdx
  pages/client-libraries/java.mdx
  pages/client-libraries/javascript.mdx
  pages/client-libraries/nodejs.mdx
  pages/client-libraries/python.mdx
  pages/client-libraries/rust.mdx
  pages/configuration/configuration-settings.mdx
  pages/configuration/data-durability-and-backup.mdx
  pages/configuration/monitoring-server.mdx
  pages/configuration/replication.mdx
  pages/configuration/server-stats.md
  pages/custom-query-modules/c/c-api.mdx
  pages/custom-query-modules/cpp/cpp-api.md
  pages/custom-query-modules/manage-query-modules.mdx
  pages/custom-query-modules/python/mock-python-api.md
  pages/custom-query-modules/python/python-api.mdx
  pages/fundamentals/indexes.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/getting-started/install-memgraph/direct-download-links.md
  pages/querying/functions.mdx
  pages/querying/performance-optimization.md
  pages/release-notes.mdx
  public/pages/advanced-algorithms/available-algorithms/algo/a_star_graph.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result1.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result2.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result3.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result4.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result5.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result6.png
  public/pages/advanced-algorithms/available-algorithms/algo/astar_result7.png
  public/pages/advanced-algorithms/available-algorithms/algo/cover_graph.png
  public/pages/advanced-algorithms/available-algorithms/algo/cover_result.png
  public/pages/advanced-algorithms/available-algorithms/algo/simplepaths_graph.png
  public/pages/advanced-algorithms/available-algorithms/refactor/extract_node_after.png
  public/pages/advanced-algorithms/available-algorithms/refactor/rename_prop_after.png
  public/pages/advanced-algorithms/available-algorithms/refactor/rename_prop_before.png
Labels: status: ship it

#296 [master < 294-improve-the-view...] Update formula
  pages/advanced-algorithms/available-algorithms/node_similarity.mdx
Labels: status: draft

#293 [master < 290-create-a-system...] Create System configuration page
  pages/configuration/system-configuration.mdx
  public/sitemap.xml
Labels: status: ready

#304 [main < 303-update-mage-...] Update MAGE installation procedure
  pages/advanced-algorithms/install-mage.mdx
Labels: status: ready

#301 [main<] QM updates
  pages/advanced-algorithms/available-algorithms/algo.mdx
  pages/advanced-algorithms/available-algorithms/betweenness_centrality.mdx
  pages/advanced-algorithms/available-algorithms/betweenness_centrality_online.mdx
  pages/advanced-algorithms/available-algorithms/biconnected_components.mdx
  pages/advanced-algorithms/available-algorithms/bipartite_matching.mdx
  pages/advanced-algorithms/available-algorithms/bridges.mdx
  pages/advanced-algorithms/available-algorithms/collections.mdx
  pages/advanced-algorithms/available-algorithms/community_detection.mdx
  pages/advanced-algorithms/available-algorithms/community_detection_online.mdx
  pages/advanced-algorithms/available-algorithms/create.mdx
  pages/advanced-algorithms/available-algorithms/cugraph.mdx
  pages/advanced-algorithms/available-algorithms/date.mdx
  pages/advanced-algorithms/available-algorithms/degree_centrality.mdx
  pages/advanced-algorithms/available-algorithms/distance_calculator.mdx
  pages/advanced-algorithms/available-algorithms/elasticsearch_synchronization.mdx
  pages/advanced-algorithms/available-algorithms/export_util.mdx
  pages/advanced-algorithms/available-algorithms/gnn_link_prediction.mdx
  pages/advanced-algorithms/available-algorithms/gnn_node_classification.mdx
  pages/advanced-algorithms/available-algorithms/graph_analyzer.mdx
  pages/advanced-algorithms/available-algorithms/graph_coloring.mdx
  pages/advanced-algorithms/available-algorithms/igraphalg.mdx
  pages/advanced-algorithms/available-algorithms/import_util.mdx
  pages/advanced-algorithms/available-algorithms/json_util.mdx
  pages/advanced-algorithms/available-algorithms/katz_centrality.mdx
  pages/advanced-algorithms/available-algorithms/katz_centrality_online.mdx
  pages/advanced-algorithms/available-algorithms/kmeans_clustering.mdx
  pages/advanced-algorithms/available-algorithms/label.mdx
  pages/advanced-algorithms/available-algorithms/llm_util.mdx
  pages/advanced-algorithms/available-algorithms/map.mdx
  pages/advanced-algorithms/available-algorithms/max_flow.mdx
  pages/advanced-algorithms/available-algorithms/merge.mdx
  pages/advanced-algorithms/available-algorithms/meta.mdx
  pages/advanced-algorithms/available-algorithms/meta_util.mdx
  pages/advanced-algorithms/available-algorithms/migrate.mdx
  pages/advanced-algorithms/available-algorithms/neighbors.mdx
  pages/advanced-algorithms/available-algorithms/node.mdx
  pages/advanced-algorithms/available-algorithms/node2vec.mdx
  pages/advanced-algorithms/available-algorithms/node2vec_online.mdx
  pages/advanced-algorithms/available-algorithms/node_similarity.mdx
  pages/advanced-algorithms/available-algorithms/nodes.mdx
  pages/advanced-algorithms/available-algorithms/nxalg.mdx
  pages/advanced-algorithms/available-algorithms/pagerank.mdx
  pages/advanced-algorithms/available-algorithms/pagerank_online.mdx
  pages/advanced-algorithms/available-algorithms/path.mdx
  pages/advanced-algorithms/available-algorithms/periodic.mdx
  pages/advanced-algorithms/available-algorithms/refactor.mdx
  pages/advanced-algorithms/available-algorithms/tgn.mdx
  pages/advanced-algorithms/available-algorithms/union_find.mdx
Labels: status: draft

#299 [memgraph-2-12-1 < ] Throw when using exists not combined with where
  pages/querying/clauses/where.md
  pages/querying/expressions.mdx
  pages/querying/functions.mdx
Labels: status: ready

#300 [memgraph-2-12-1 < ] Detach delete path
  pages/querying/read-and-modify-data.md
Labels: status: ready

#307 [memgraph-2-12-1 < ] Change query plan cache flag
  pages/configuration/configuration-settings.mdx
Labels: status: ready

#326 Update signature of temporal functions
  pages/querying/functions.mdx
Labels: status: ready

#328 Remove default memory proc limit
  pages/custom-query-modules/manage-query-modules.mdx
Labels: status: ready

#327 Add docker copy custom component
  components/code-snippet/CodeSnippet.tsx
  components/link-click/LinkClick.tsx
  pages/client-libraries/go.mdx
  pages/client-libraries/graphql.mdx
  pages/client-libraries/javascript.mdx
  pages/client-libraries/nodejs.mdx
  pages/client-libraries/php.mdx
  pages/client-libraries/python.mdx
  pages/getting-started.mdx
  pages/getting-started/first-steps-with-docker.mdx
  pages/getting-started/first-steps-with-memgraph.mdx
  pages/getting-started/install-memgraph.mdx
  pages/getting-started/install-memgraph/debian.mdx
  pages/getting-started/install-memgraph/direct-download-links.md
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/getting-started/install-memgraph/docker.mdx
  pages/getting-started/install-memgraph/rpm-package.mdx
  pages/getting-started/install-memgraph/ubuntu.mdx
  pages/getting-started/install-memgraph/wsl.mdx
  public/copied-icon-dark.svg
  public/copied-icon.svg
  public/copy-icon-dark.svg
  public/copy-icon.svg
Labels: status: ship it

#323 [main<] Add Lab 2.9.1 release notes
  pages/release-notes.mdx
Labels: status: ship it

#330 [main<] Add Kafka Connect documentation
  pages/data-streams/kafka.mdx
  public/pages/data-streams/kafka/kafka-connect-tab.png
  public/pages/data-streams/kafka/kafka-topics-test.png
  public/pages/data-streams/kafka/kafka-topics.png
  public/pages/data-streams/kafka/lab-create-nodes.png
Labels: status: change

#317 [main < memgraph-2-12-1] Release 2-12-1
  pages/configuration/configuration-settings.mdx
  pages/configuration/server-stats.md
  pages/custom-query-modules/manage-query-modules.mdx
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/querying/clauses/where.md
  pages/querying/expressions.mdx
  pages/querying/functions.mdx
  pages/querying/read-and-modify-data.md
  pages/release-notes.mdx
Labels: status: ship it

#335 [main<] Improving QM docs
  pages/advanced-algorithms/available-algorithms/nxalg.mdx
  pages/advanced-algorithms/available-algorithms/pagerank.mdx
  pages/advanced-algorithms/available-algorithms/pagerank_online.mdx
Labels: status: draft

#338 [memgraph-2-13<] Add docs for text query modules
  pages/advanced-algorithms/available-algorithms/text.mdx
Labels: status: ready

#344 Implement constant time info retrieval
  pages/configuration/configuration-settings.mdx
  pages/querying/schema.mdx
Labels: status: ready
