Repository memgraph/documentation, pull requests merged in 2024-11, with the labels that each got.

#1006 Added links for Ubuntu 24.04 toolchain v5
  pages/getting-started/build-memgraph-from-source.mdx
Labels: priority: medium (missing info), status: ready

#1014 Add Leiden community detection algorithm docs
  pages/advanced-algorithms/available-algorithms.md
  pages/advanced-algorithms/available-algorithms/leiden_community_detection.mdx
Labels: memgraph-2-21

#1007 Update pagerank online documentation
  pages/advanced-algorithms/available-algorithms/pagerank_online.mdx
Labels: priority: medium (missing info), status: ready

#1027 Add explanation for exception handling in Leiden community detection algorithm
  pages/advanced-algorithms/available-algorithms/leiden_community_detection.mdx
Labels: memgraph-2-21

#1018 Spatial index and data type docs
  pages/fundamentals/data-types.mdx
  pages/fundamentals/indexes.mdx
  pages/querying/functions.mdx
  pages/querying/query-plan.mdx
Labels: memgraph-2-21

#1020 Update algorithm pages
  pages/advanced-algorithms/available-algorithms/algo.mdx
  pages/advanced-algorithms/available-algorithms/betweenness_centrality.mdx
  pages/advanced-algorithms/available-algorithms/biconnected_components.mdx
  pages/advanced-algorithms/available-algorithms/bipartite_matching.mdx
  pages/advanced-algorithms/available-algorithms/bridges.mdx
  pages/advanced-algorithms/available-algorithms/community_detection.mdx
  pages/advanced-algorithms/available-algorithms/community_detection_online.mdx
  pages/advanced-algorithms/available-algorithms/create.mdx
  pages/advanced-algorithms/available-algorithms/cugraph.mdx
  pages/advanced-algorithms/available-algorithms/cycles.mdx
  pages/advanced-algorithms/available-algorithms/degree_centrality.mdx
  pages/advanced-algorithms/available-algorithms/distance_calculator.mdx
  pages/advanced-algorithms/available-algorithms/elasticsearch_synchronization.mdx
  pages/advanced-algorithms/available-algorithms/export_util.mdx
  pages/advanced-algorithms/available-algorithms/gnn_link_prediction.mdx
  pages/advanced-algorithms/available-algorithms/gnn_node_classification.mdx
  pages/advanced-algorithms/available-algorithms/graph_analyzer.mdx
  pages/advanced-algorithms/available-algorithms/graph_coloring.mdx
  pages/advanced-algorithms/available-algorithms/graph_util.mdx
  pages/advanced-algorithms/available-algorithms/igraphalg.mdx
  pages/advanced-algorithms/available-algorithms/katz_centrality_online.mdx
  pages/advanced-algorithms/available-algorithms/kmeans_clustering.mdx
  pages/advanced-algorithms/available-algorithms/llm_util.mdx
  pages/advanced-algorithms/available-algorithms/max_flow.mdx
  pages/advanced-algorithms/available-algorithms/merge.mdx
  pages/advanced-algorithms/available-algorithms/meta_util.mdx
  pages/advanced-algorithms/available-algorithms/node.mdx
  pages/advanced-algorithms/available-algorithms/node2vec.mdx
  pages/advanced-algorithms/available-algorithms/node2vec_online.mdx
  pages/advanced-algorithms/available-algorithms/node_similarity.mdx
  pages/advanced-algorithms/available-algorithms/nodes.mdx
  pages/advanced-algorithms/available-algorithms/nxalg.mdx
  pages/advanced-algorithms/available-algorithms/pagerank.mdx
  pages/advanced-algorithms/available-algorithms/pagerank_online.mdx
  pages/advanced-algorithms/available-algorithms/path.mdx
  pages/advanced-algorithms/available-algorithms/refactor.mdx
  pages/advanced-algorithms/available-algorithms/set_cover.mdx
  pages/advanced-algorithms/available-algorithms/set_property.mdx
  pages/advanced-algorithms/available-algorithms/tgn.mdx
  pages/advanced-algorithms/available-algorithms/tsp.mdx
  pages/advanced-algorithms/available-algorithms/union_find.mdx
  pages/advanced-algorithms/available-algorithms/uuid_generator.mdx
  pages/advanced-algorithms/available-algorithms/vrp.mdx
  pages/advanced-algorithms/available-algorithms/weakly_connected_components.mdx
  pages/advanced-algorithms/available-algorithms/xml_module.mdx
Labels: memgraph-2-21

#1029 Schema info v2
  pages/fundamentals/storage-memory-usage.mdx
  pages/querying/schema.mdx
Labels: future release, memgraph-2-21

#1009 Memgraph 2.21 documentation changes
  pages/advanced-algorithms/available-algorithms.md
  pages/advanced-algorithms/available-algorithms/algo.mdx
  pages/advanced-algorithms/available-algorithms/betweenness_centrality.mdx
  pages/advanced-algorithms/available-algorithms/biconnected_components.mdx
  pages/advanced-algorithms/available-algorithms/bipartite_matching.mdx
  pages/advanced-algorithms/available-algorithms/bridges.mdx
  pages/advanced-algorithms/available-algorithms/community_detection.mdx
  pages/advanced-algorithms/available-algorithms/community_detection_online.mdx
  pages/advanced-algorithms/available-algorithms/create.mdx
  pages/advanced-algorithms/available-algorithms/cugraph.mdx
  pages/advanced-algorithms/available-algorithms/cycles.mdx
  pages/advanced-algorithms/available-algorithms/degree_centrality.mdx
  pages/advanced-algorithms/available-algorithms/distance_calculator.mdx
  pages/advanced-algorithms/available-algorithms/elasticsearch_synchronization.mdx
  pages/advanced-algorithms/available-algorithms/export_util.mdx
  pages/advanced-algorithms/available-algorithms/gnn_link_prediction.mdx
  pages/advanced-algorithms/available-algorithms/gnn_node_classification.mdx
  pages/advanced-algorithms/available-algorithms/graph_analyzer.mdx
  pages/advanced-algorithms/available-algorithms/graph_coloring.mdx
  pages/advanced-algorithms/available-algorithms/graph_util.mdx
  pages/advanced-algorithms/available-algorithms/igraphalg.mdx
  pages/advanced-algorithms/available-algorithms/katz_centrality_online.mdx
  pages/advanced-algorithms/available-algorithms/kmeans_clustering.mdx
  pages/advanced-algorithms/available-algorithms/leiden_community_detection.mdx
  pages/advanced-algorithms/available-algorithms/llm_util.mdx
  pages/advanced-algorithms/available-algorithms/max_flow.mdx
  pages/advanced-algorithms/available-algorithms/merge.mdx
  pages/advanced-algorithms/available-algorithms/meta_util.mdx
  pages/advanced-algorithms/available-algorithms/node.mdx
  pages/advanced-algorithms/available-algorithms/node2vec.mdx
  pages/advanced-algorithms/available-algorithms/node2vec_online.mdx
  pages/advanced-algorithms/available-algorithms/node_similarity.mdx
  pages/advanced-algorithms/available-algorithms/nodes.mdx
  pages/advanced-algorithms/available-algorithms/nxalg.mdx
  pages/advanced-algorithms/available-algorithms/pagerank.mdx
  pages/advanced-algorithms/available-algorithms/pagerank_online.mdx
  pages/advanced-algorithms/available-algorithms/path.mdx
  pages/advanced-algorithms/available-algorithms/refactor.mdx
  pages/advanced-algorithms/available-algorithms/set_cover.mdx
  pages/advanced-algorithms/available-algorithms/set_property.mdx
  pages/advanced-algorithms/available-algorithms/tgn.mdx
  pages/advanced-algorithms/available-algorithms/tsp.mdx
  pages/advanced-algorithms/available-algorithms/union_find.mdx
  pages/advanced-algorithms/available-algorithms/uuid_generator.mdx
  pages/advanced-algorithms/available-algorithms/vrp.mdx
  pages/advanced-algorithms/available-algorithms/weakly_connected_components.mdx
  pages/advanced-algorithms/available-algorithms/xml_module.mdx
  pages/custom-query-modules/cpp/cpp-api.md
  pages/custom-query-modules/cpp/cpp-example.mdx
  pages/data-visualization/install-and-connect.mdx
  pages/data-visualization/user-manual/custom-ssl-certificates.mdx
  pages/fundamentals/data-types.mdx
  pages/fundamentals/indexes.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/getting-started/build-memgraph-from-source.mdx
  pages/querying/differences-in-cypher-implementations.mdx
  pages/querying/functions.mdx
  pages/querying/query-plan.mdx
  pages/querying/schema.mdx
  pages/release-notes.mdx
Labels: status: waiting (blocked), future release, memgraph-2-21, release-pr

#1033 new: Add Lab release notes
  pages/release-notes.mdx
Labels: status: ready

#1038 new: Add release notes for Lab 2.18.1
  pages/release-notes.mdx
Labels: status: ready

#1040 new: Add release notes for Lab 2.18.2
  pages/release-notes.mdx
Labels: status: ready

#1019 Add Memgraph as knowledge graph
  next.config.js
  pages/_meta.json
  pages/ai-ecosystem/graph-rag.mdx
  pages/data-migration.mdx
  pages/data-migration/best-practices.mdx
  pages/data-modeling.mdx
  pages/data-modeling/_meta.json
  pages/data-modeling/knowledge-graph.mdx
  pages/fundamentals.md
  pages/fundamentals/_meta.json
  public/pages/data-modeling/graph-modeling/graph-modeling-describe-domain.png
  public/pages/data-modeling/graph-modeling/graph-modeling-labels.png
  public/pages/data-modeling/graph-modeling/graph-modeling-mapping-relationships.png
  public/pages/data-modeling/graph-modeling/graph-modeling-nodes.png
  public/pages/data-modeling/graph-modeling/graph-modeling-properties.png
  public/pages/data-modeling/graph-modeling/graph-modeling-property-or-relationship.png
  public/pages/data-modeling/graph-modeling/graph-modeling-relationships.png
  public/pages/data-modeling/graph-modeling/graph-modeling-storing-properties.png
  public/pages/data-modeling/graph-modeling/graph-modeling-un-directed-graph.png
  public/pages/data-modeling/graph-modeling/graph-modeling-weighted-graph.png
  public/pages/data-modeling/graph-modeling/graph-modeling-whiteboard.png
  public/pages/data-modeling/knowledge-graph/project-management-full-graph.png
  public/pages/data-modeling/knowledge-graph/project-management-graph.png
  public/pages/data-modeling/knowledge-graph/project-management-progression-graph.png
Labels: priority: medium (missing info)

#1056 fix: Fix the incorrect inline reference for GSS
  pages/data-visualization/graph-style-script/directive-properties.md
Labels: status: ready, Lab docs, bugfix

#1055 Fixed typo on ha (attempt 2)
  pages/clustering/high-availability.mdx
Labels: priority: high (error)

#988 Add 'GRANT DATABASE' to rbac
  pages/database-management/authentication-and-authorization/role-based-access-control.mdx
Labels: priority: low (improvements)

#1051 Add vector search to experimental page
  pages/database-management.md
  pages/database-management/configuration.mdx
  pages/database-management/experimental-features.mdx
  pages/querying/_meta.json
  pages/querying/vector-search.mdx
Labels: memgraph-2-22, feature

#1054 new: Add Lab 2.19 changelog and base path docs
  pages/data-visualization/user-manual/custom-base-path.mdx
  pages/release-notes.mdx
Labels: status: ready, Lab docs, feature

#1062 Text, link prediction and node classification return
  pages/advanced-algorithms/available-algorithms/gnn_link_prediction.mdx
  pages/advanced-algorithms/available-algorithms/gnn_node_classification.mdx
  pages/advanced-algorithms/available-algorithms/text.mdx
  pages/release-notes.mdx
Labels: memgraph-2-22, bugfix

#1063 Spatial withinbbox and other improvements docs
  pages/fundamentals/indexes.mdx
  pages/release-notes.mdx
Labels: memgraph-2-22, feature

#1053 Extend periodic snapshot interface
  pages/data-migration/best-practices.mdx
  pages/database-management/backup-and-restore.mdx
  pages/database-management/configuration.mdx
  pages/fundamentals/data-durability.mdx
  pages/fundamentals/storage-memory-usage.mdx
Labels: feature

#1037 Memgraph 2.22 documentation changes
  pages/advanced-algorithms/available-algorithms/gnn_link_prediction.mdx
  pages/advanced-algorithms/available-algorithms/gnn_node_classification.mdx
  pages/advanced-algorithms/available-algorithms/text.mdx
  pages/clustering/high-availability.mdx
  pages/data-migration/best-practices.mdx
  pages/data-visualization/user-manual.mdx
  pages/data-visualization/user-manual/custom-base-path.mdx
  pages/database-management.mdx
  pages/database-management/backup-and-restore.mdx
  pages/database-management/configuration.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/database-management/experimental-features.mdx
  pages/fundamentals/data-durability.mdx
  pages/fundamentals/indexes.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/getting-started/install-memgraph/kubernetes.mdx
  pages/querying/_meta.json
  pages/querying/vector-search.mdx
  pages/release-notes.mdx
Labels: release
