Repository memgraph/documentation, pull requests merged in 2024-02, with the labels that each got.

#452 [master < 450-update-default...] Update default flag values in the docs
  pages/configuration/configuration-settings.mdx
  public/sitemap.xml
Labels: status: ship it

#455 [main<change-search-behavior] Change search behavior
  pages/_document.js
Labels: status: ready, status: ship it

#457 [main < fix-menu-link] Fix menu link
  pages/advanced-algorithms/available-algorithms/_meta.json
Labels: status: ship it

#449 Update csv import
  pages/data-migration/csv.mdx
  pages/data-visualization/user-manual.mdx
  public/pages/data-migration/csv/csv_import.png
  public/pages/data-migration/csv/data_schema.png
  public/pages/data-migration/csv/file_upload.png
  public/pages/data-migration/csv/graph_illustration.png
  public/pages/data-migration/csv/graph_illustration_1.png
  public/pages/data-migration/csv/import_successful.png
  public/pages/data-migration/csv/multiple_people_nodes.png
  public/pages/data-migration/csv/multiple_people_relationships.png
  public/pages/data-migration/csv/multiple_restaurant_nodes.png
  public/pages/data-migration/csv/multiple_restaurants_relationships.png
  public/pages/data-migration/csv/people_nodes_with_header.png
  public/pages/data-migration/csv/people_nodes_without_header.png
  public/pages/data-migration/csv/people_relationships_with_header.png
  public/pages/data-migration/csv/people_relationships_without_header.png
  public/pages/data-migration/csv/single_people_nodes.png
  public/pages/data-migration/csv/single_people_relationships.png
  public/pages/data-visualization/lab-user-manual/export.png
  public/pages/data-visualization/lab-user-manual/import.png
Labels: status: ready

#462 Update broken link
  pages/data-migration/csv.mdx
Labels: status: ship it

#465 [master < 463-explain-serialization...] Add a new documentation page for Serialization errors
  pages/help-center/errors/_meta.json
  pages/help-center/errors/serialization.mdx
Labels: status: ready

#471 Update image
  public/pages/fundamentals/graph-modeling/graph-modeling-describe-domain.png
Labels: status: ship it

#473 Update docker-compose file examples
  pages/getting-started/install-memgraph/docker-compose.mdx
Labels: status: ship it

#503 Add delete workaround
  pages/client-libraries/python.mdx
  pages/querying/clauses/delete.md
Labels: status: ready, status: ship it

#506 [main < 489-add-link] Update direct download links callout
  pages/getting-started/install-memgraph/debian.mdx
  pages/getting-started/install-memgraph/rpm-package.mdx
  pages/getting-started/install-memgraph/ubuntu.mdx
  pages/getting-started/install-memgraph/wsl.mdx
Labels: status: ship it

#508 [main < 451-add-migrate-module...] Update data migration guide
  pages/data-migration.mdx
Labels: status: ship it

#485 [memgraph-2-15<] Add propertySize function
  pages/_document.js
  pages/advanced-algorithms/available-algorithms/_meta.json
  pages/advanced-algorithms/built-in-graph-algorithms.mdx
  pages/client-libraries/c-sharp.mdx
  pages/client-libraries/go.mdx
  pages/client-libraries/graphql.mdx
  pages/client-libraries/java.mdx
  pages/client-libraries/javascript.mdx
  pages/client-libraries/nodejs.mdx
  pages/client-libraries/php.mdx
  pages/client-libraries/python.mdx
  pages/client-libraries/rust.mdx
  pages/configuration/configuration-settings.mdx
  pages/configuration/ssl-encryption.mdx
  pages/data-migration/csv.mdx
  pages/data-migration/json.mdx
  pages/data-streams/manage-streams-query.md
  pages/data-visualization/user-manual.mdx
  pages/getting-started/install-memgraph/debian.mdx
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/getting-started/install-memgraph/docker-compose.mdx
  pages/help-center/errors/_meta.json
  pages/help-center/errors/serialization.mdx
  pages/querying/functions.mdx
  public/pages/data-migration/csv/csv_import.png
  public/pages/data-migration/csv/data_schema.png
  public/pages/data-migration/csv/file_upload.png
  public/pages/data-migration/csv/graph_illustration.png
  public/pages/data-migration/csv/graph_illustration_1.png
  public/pages/data-migration/csv/import_successful.png
  public/pages/data-migration/csv/multiple_people_nodes.png
  public/pages/data-migration/csv/multiple_people_relationships.png
  public/pages/data-migration/csv/multiple_restaurant_nodes.png
  public/pages/data-migration/csv/multiple_restaurants_relationships.png
  public/pages/data-migration/csv/people_nodes_with_header.png
  public/pages/data-migration/csv/people_nodes_without_header.png
  public/pages/data-migration/csv/people_relationships_with_header.png
  public/pages/data-migration/csv/people_relationships_without_header.png
  public/pages/data-migration/csv/single_people_nodes.png
  public/pages/data-migration/csv/single_people_relationships.png
  public/pages/data-visualization/lab-user-manual/export.png
  public/pages/data-visualization/lab-user-manual/import.png
  public/pages/fundamentals/graph-modeling/graph-modeling-describe-domain.png
  public/sitemap.xml
Labels: status: ready

#507 [memgraph-2-15<] Expand parameters page
  pages/querying/expressions.mdx
Labels: status: ready

#480 [memgraph-2-15<] Update docker compose documentation
  components/code-snippet/CodeSnippet.tsx
  pages/client-libraries/c-sharp.mdx
  pages/client-libraries/go.mdx
  pages/client-libraries/graphql.mdx
  pages/client-libraries/java.mdx
  pages/client-libraries/javascript.mdx
  pages/client-libraries/nodejs.mdx
  pages/client-libraries/php.mdx
  pages/client-libraries/python.mdx
  pages/client-libraries/rust.mdx
  pages/getting-started.mdx
  pages/getting-started/first-steps-with-docker.mdx
  pages/getting-started/first-steps-with-memgraph.mdx
  pages/getting-started/install-memgraph.mdx
  pages/getting-started/install-memgraph/debian.mdx
  pages/getting-started/install-memgraph/docker-compose.mdx
  pages/getting-started/install-memgraph/docker.mdx
  pages/getting-started/install-memgraph/rpm-package.mdx
  pages/getting-started/install-memgraph/wsl.mdx
Labels: status: ready

#476 [memgraph-2-15<] System replication
  pages/configuration/configuration-settings.mdx
  pages/configuration/experimental-replication.mdx
  pages/configuration/replication.mdx
  pages/help-center/errors/replication.mdx
  pages/help-center/faq.md
Labels: status: ready

#491 High availability docs
  pages/configuration/_meta.json
  pages/configuration/configuration-settings.mdx
  pages/configuration/high-availability.mdx
Labels: status: ready

#487 Add mgconsole cypherl output format docs
  pages/getting-started/cli.mdx
Labels: priority: high (error), status: ready

#511 new: Add Lab 2.12 release notes
  pages/release-notes.mdx
Labels: status: ready, status: ship it

#492 Add section about index creation and IN_MEMORY_ANALYTICAL in migrate docs
  pages/data-migration/migrate-from-neo4j.mdx
  pages/data-migration/migrate-from-rdbms.md
Labels: status: ship it

#486 Document valuetype function
  pages/querying/functions.mdx
Labels: status: ready
