Repository memgraph/documentation, pull requests merged in 2024-04, with the labels that each got.

#584 [<memgraph-2-15-1] Memgraph 2.15.1 docs
  pages/configuration/_meta.json
  pages/configuration/configuration-settings.mdx
  pages/configuration/text-search.mdx
  pages/custom-query-modules/c/c-api.mdx
  pages/custom-query-modules/cpp/cpp-api.md
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/release-notes.mdx
Labels: status: ready, status: ship it, future release

#648 New: Add Lab v2.13.0 release notes
  pages/release-notes.mdx
Labels: status: ready

#501 Add periodic delete
  pages/advanced-algorithms/available-algorithms/periodic.mdx
Labels: status: ready, future release

#651 [memgraph-2.15.2 < T651] Fix text search usage example
  pages/configuration/text-search.mdx
Labels: priority: high (error), status: ready, future release

#647 [memgraph-2-16 < T647] Documentation for date.add
  next.config.js
  pages/advanced-algorithms/available-algorithms/date.mdx
  pages/advanced-algorithms/built-in-graph-algorithms.mdx
  pages/client-libraries.mdx
  pages/configuration.md
  pages/configuration/_meta.json
  pages/configuration/configuration-settings.mdx
  pages/configuration/experimental-replication.mdx
  pages/configuration/high-availability.mdx
  pages/configuration/monitoring-server.mdx
  pages/configuration/text-search.mdx
  pages/custom-query-modules/c/c-api.mdx
  pages/custom-query-modules/cpp/cpp-api.md
  pages/data-visualization/user-manual.mdx
  pages/fundamentals/constraints.mdx
  pages/fundamentals/indexes.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/getting-started.mdx
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/getting-started/install-memgraph/docker-compose.mdx
  pages/getting-started/install-memgraph/docker.mdx
  pages/getting-started/install-memgraph/memgraph-cloud.mdx
  pages/help-center/errors/_meta.json
  pages/help-center/errors/conflicting-transactions.mdx
  pages/help-center/errors/replication.mdx
  pages/help-center/faq.md
  pages/querying/_meta.json
  pages/querying/best-practices.mdx
  pages/querying/clauses/_meta.json
  pages/querying/clauses/explain.md
  pages/querying/clauses/foreach.mdx
  pages/querying/clauses/profile.md
  pages/querying/differences-in-cypher-implementations.md
  pages/querying/differences-in-cypher-implementations.mdx
  pages/querying/functions.mdx
  pages/querying/performance-optimization.md
  pages/querying/query-plan.mdx
  pages/querying/schema.mdx
  public/pages/advanced-algorithms/allshortest.png
  public/pages/advanced-algorithms/bfs.gif
  public/pages/advanced-algorithms/dfs.gif
  public/pages/advanced-algorithms/dijkstra.gif
  public/pages/advanced-algorithms/dijkstra.png
  public/pages/advanced-algorithms/graph.png
  public/pages/querying/best-practices/query-optimization-lab-got-1.png
  public/pages/querying/best-practices/query-optimization-lab-got-2.png
  public/pages/querying/best-practices/query-optimization-lab-got-3.png
  public/pages/querying/best-practices/query-optimization-lab-got-4.png
  public/pages/querying/best-practices/query-optimization-lab-got-5.png
  public/pages/querying/best-practices/query-optimization-lab-got-6.png
  public/pages/querying/best-practices/query-optimization-lab-got-7.png
  public/sitemap.xml
Labels: status: ready, future release

#616 Drop graph
  pages/querying/clauses/delete.md
  pages/querying/clauses/drop-graph.mdx
  pages/querying/differences-in-cypher-implementations.mdx
  pages/querying/read-and-modify-data.md
Labels: status: ready, future release

#652 [main <memgraph-2-15-2] Memgraph 2.15.2 docs
  pages/configuration/text-search.mdx
  pages/release-notes.mdx
Labels: status: ready, future release

#502 Add documentation for edge-type indexing
  pages/fundamentals/indexes.mdx
Labels: status: ready, future release

#613 Implement automatic index creation
  pages/configuration/configuration-settings.mdx
  pages/fundamentals/indexes.mdx
Labels: status: ready, future release

#650 [memgraph-2.16 < ] Forbid merge with null properties
  pages/querying/clauses/merge.mdx
Labels: future release

#654 [memgraph-2.16 < ] Update schema docs
  pages/querying/schema.mdx
Labels: status: ready

#658 [memgraph-2-16 <] Query execution API
  pages/custom-query-modules/c/c-api.mdx
  pages/custom-query-modules/cpp/cpp-api.md
Labels: status: ready, customer

#661 Updates to native install process
  pages/getting-started/install-memgraph/debian.mdx
  pages/getting-started/install-memgraph/rpm-package.mdx
  pages/getting-started/install-memgraph/ubuntu.mdx
Labels: status: ready

#666 [memgraph-2-16 < ] Update load csv docs
  pages/data-migration/csv.mdx
Labels: status: ready

#606 Fetch edge by edge id
  pages/configuration/configuration-settings.mdx
Labels: status: ready, future release

#656 [memgraph-2-16 < ] Query execution in MAGE module refactor
  pages/advanced-algorithms/available-algorithms/conditional_execution.mdx
Labels: status: ready, customer

#564 [memgraph-2-16<] Update Memgraph 2.16 release notes
  pages/release-notes.mdx
Labels: future release

#685 Update DROP GRAPH docs
  pages/querying/clauses.mdx
  pages/querying/clauses/_meta.json
  pages/querying/clauses/drop-graph.mdx
Labels: status: ship it

#690 Update starting Memgraph with Docker
  pages/data-migration/migrate-from-neo4j.mdx
Labels: priority: low (improvements), status: ready, status: ship it

#700 [manin < 688-update-lab-installation-manual] Update Lab installation manual
  pages/data-visualization/install-and-connect.mdx
Labels: status: ready

#645 Create Build Memgraph from source docs page
  pages/getting-started/build-memgraph-from-source.mdx
Labels: status: ready

#691 Refactor the configuration guide
  pages/_meta.json
  pages/configuration/_meta.json
  pages/configuration/configuration-settings.mdx
Labels: status: ready

#705 Revamp getting started
  next.config.js
  pages/data-migration/migrate-from-neo4j.mdx
  pages/data-visualization/install-and-connect.mdx
  pages/getting-started.mdx
  pages/getting-started/_meta.json
  pages/getting-started/first-steps-with-memgraph.mdx
  pages/getting-started/install-memgraph.mdx
  pages/getting-started/install-memgraph/docker.mdx
  pages/index.mdx
Labels: status: ready, status: ship it

#711 Add querying tips
  pages/querying/best-practices.mdx
Labels: status: ready

#709 Update config settings for Docker Compose
  pages/configuration/configuration-settings.mdx
  pages/getting-started/install-memgraph/docker-compose.mdx
Labels: status: ready

#708 Replace Memgraph Platform image with Memgraph MAGE image where applicable
  pages/advanced-algorithms/utilize-networkx.md
  pages/configuration/replication.mdx
  pages/configuration/security.mdx
  pages/configuration/ssl-encryption.mdx
  pages/custom-query-modules/cpp/cpp-example.mdx
  pages/custom-query-modules/manage-query-modules.mdx
  pages/data-migration/migrate-from-rdbms.mdx
  pages/data-streams/transformation-modules.mdx
  pages/getting-started/cli.mdx
  pages/getting-started/first-steps-with-docker.mdx
Labels: status: ready

#692 Add section about configuring user authentication in Docker Compose
  pages/configuration/configuration-settings.mdx
  pages/getting-started/install-memgraph/docker-compose.mdx
Labels: status: ready

#727 Added health check section
  pages/getting-started/install-memgraph/docker-compose.mdx
Labels: status: ready
