Repository memgraph/documentation, pull requests merged in 2024-08, with the labels that each got.

#947 [main < 945-wrong-link] Update link for how-to guide on connecting to data streams
  pages/data-visualization/user-manual.mdx
Labels: status: ready

#909 Add monitoring and logs connection examples
  pages/database-management/configuration.mdx
  pages/database-management/monitoring.mdx
Labels: status: ready

#958 [main < sitemap-update-20240802] Update sitemap
  public/sitemap.xml
Labels: status: ship it

#964 Add info about data replication in analytical storage mode
  pages/clustering.mdx
  pages/clustering/high-availability.mdx
  pages/clustering/replication.mdx
  pages/fundamentals/storage-memory-usage.mdx
Labels: status: ready

#952 Add documentation for SHOW USERS
  pages/database-management/authentication-and-authorization/users.mdx
Labels: status: ready

#951 Update getting-started docs to specify memgraph-mage container
  pages/getting-started.mdx
Labels: status: ready

#873 Added description for hiding sensitive information under database-man…
  pages/clustering/high-availability.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/database-management/logs.mdx
Labels: status: ready, future release, customer

#955 [main < 954-remove-unnecessary-sentence] Remove redundant sentence
  pages/database-management/ssl-encryption.mdx
Labels: status: ready

#913 TTL docs
  pages/querying/_meta.json
  pages/querying/time-to-live.mdx
Labels: status: ready

#950 Define user with a pre-hashed password
  pages/database-management/authentication-and-authorization/users.mdx
Labels: Docs Ready - Pending Dev Merge

#968 Fix errors in SSO documentation
  pages/data-visualization/user-manual/single-sign-on.mdx
  pages/database-management/authentication-and-authorization/auth-system-integrations.mdx
Labels: priority: high (error), customer

#937 [main < 925-fix-perdiodic-page] Move the example to the bottom of the page
  pages/advanced-algorithms/available-algorithms/periodic.mdx
Labels: status: ready

#970 fix: Add better explanation for Cloud snapshots vs CREATE SNAPSHOT command
  pages/getting-started/install-memgraph/memgraph-cloud.mdx
  pages/help-center/errors/snapshots.mdx
Labels: status: ready

#965 new: Add Lab 2.16 release notes and connection types docs
  pages/advanced-algorithms/available-algorithms/periodic.mdx
  pages/data-visualization/install-and-connect.mdx
  pages/data-visualization/user-manual.mdx
  pages/data-visualization/user-manual/connection-types.mdx
  pages/data-visualization/user-manual/single-sign-on.mdx
  pages/database-management/authentication-and-authorization/auth-system-integrations.mdx
  pages/release-notes.mdx
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-color-pick.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-color-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-coordinator-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-ha-cluster-input.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-ha-cluster-status.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-ha-cluster-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-main-instance-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-replica-instance-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-replication-status.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-select.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-standalone-input.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-standalone-success.png
Labels: status: ready

#892 [memgraph-2-19 < memgraph-2-19-relase-notes] Release notes for Memgraph 2.19
  pages/release-notes.mdx
Labels: status: ready, future release

#959 Fix monitoring documentation indents and typo
  pages/database-management/monitoring.mdx
Labels: status: ready

#946 LocalDateTime and timezone updates
  pages/database-management/configuration.mdx
  pages/fundamentals/data-types.mdx
Labels: status: ready

#960 [Memgraph-2.19 < Helm chart updates] Add configs and notes
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, memgraph-2-19

#963 Show active users
  pages/database-management/server-stats.md
Labels: status: ready, customer, memgraph-2-19

#935 Add periodic commit documentation
  pages/data-migration/best-practices.mdx
  pages/database-management/monitoring.mdx
  pages/querying/clauses.mdx
  pages/querying/query-plan.mdx
  pages/querying/read-and-modify-data.md
Labels: status: ready, future release, customer, memgraph-2-19

#967 Mage Node2Vec update after bumping Gensim version
  pages/advanced-algorithms/available-algorithms/node2vec.mdx
Labels: status: ready, future release, memgraph-2-19

#949 Change wording in show instances part of HA docs
  pages/clustering/high-availability.mdx
Labels: status: ready, memgraph-2-19

#975 Add Ubuntu 24.04
  pages/clustering/high-availability.mdx
  pages/getting-started/install-memgraph/amazon-linux.mdx
  pages/getting-started/install-memgraph/centos.mdx
  pages/getting-started/install-memgraph/debian.mdx
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/getting-started/install-memgraph/docker.mdx
  pages/getting-started/install-memgraph/fedora.mdx
  pages/getting-started/install-memgraph/redhat.mdx
  pages/getting-started/install-memgraph/rocky.mdx
  pages/getting-started/install-memgraph/ubuntu.mdx
Labels: status: ready

#893 [main < memgraph-2-19] Memgraph 2.19 documentation
  pages/advanced-algorithms/available-algorithms/node2vec.mdx
  pages/clustering/high-availability.mdx
  pages/data-migration/best-practices.mdx
  pages/data-visualization/install-and-connect.mdx
  pages/data-visualization/user-manual.mdx
  pages/data-visualization/user-manual/connection-types.mdx
  pages/database-management/authentication-and-authorization/users.mdx
  pages/database-management/configuration.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/database-management/logs.mdx
  pages/database-management/monitoring.mdx
  pages/database-management/server-stats.md
  pages/fundamentals/data-types.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/getting-started/install-memgraph/amazon-linux.mdx
  pages/getting-started/install-memgraph/centos.mdx
  pages/getting-started/install-memgraph/debian.mdx
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/getting-started/install-memgraph/docker.mdx
  pages/getting-started/install-memgraph/fedora.mdx
  pages/getting-started/install-memgraph/kubernetes.mdx
  pages/getting-started/install-memgraph/redhat.mdx
  pages/getting-started/install-memgraph/rocky.mdx
  pages/getting-started/install-memgraph/ubuntu.mdx
  pages/querying/_meta.json
  pages/querying/clauses.mdx
  pages/querying/query-plan.mdx
  pages/querying/read-and-modify-data.md
  pages/querying/time-to-live.mdx
  pages/release-notes.mdx
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-color-pick.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-color-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-coordinator-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-ha-cluster-input.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-ha-cluster-status.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-ha-cluster-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-main-instance-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-replica-instance-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-replication-status.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-select.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-standalone-input.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-standalone-success.png
  public/sitemap.xml
Labels: future release

#971 Adds warning regarding the use of TTL label and ttl property
  pages/querying/time-to-live.mdx
Labels: status: ready, memgraph-2-19

#976 fix: Fix broken url in release notes
  pages/release-notes.mdx
Labels: status: ready

#977 [main < sitemap-update-20240816] Update sitemap
  public/sitemap.xml
Labels: status: ship it

#982 Remove Kruno
  .github/CODEOWNERS
Labels: status: ready

#981 [main < optimize-images-20240819] Optimize images
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-color-pick.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-color-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-coordinator-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-ha-cluster-input.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-ha-cluster-status.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-ha-cluster-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-main-instance-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-replica-instance-success.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-replication-status.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-select.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-standalone-input.png
  public/pages/data-visualization/lab-user-manual/connection-types/conn-type-standalone-success.png
Labels: status: ready

#984 Add improvements for HA docs
  pages/clustering/high-availability.mdx
Labels: priority: high (error), status: ready
