Repository memgraph/documentation, pull requests merged in 2024-07, with the labels that each got.

#881 Add hops limit docs
  pages/advanced-algorithms/deep-path-traversal.mdx
Labels: status: ready

#788 Peak memory observation in the system
  pages/data-migration/best-practices.mdx
  pages/database-management/server-stats.md
  pages/fundamentals/storage-memory-usage.mdx
Labels: priority: low (improvements), status: ready, status: ship it, future release, Docs Ready - Pending Dev Merge

#878 Update envs for HA
  pages/database-management/configuration.mdx
Labels: future release

#829 Add cloud provider guides (AWS, Azure, GCP)
  pages/deployment/_meta.json
  pages/deployment/aws.mdx
  pages/deployment/azure.mdx
  pages/deployment/gcp.mdx
  public/sitemap.xml
Labels: status: ready, status: ship it

#877 Add callout for important force reset notice
  pages/clustering/high-availability.mdx
Labels: future release

#852 Enum datatype (v1)
  pages/fundamentals/data-types.mdx
  pages/fundamentals/graph-modeling.md
  pages/fundamentals/storage-memory-usage.mdx
  pages/querying/clauses.mdx
  pages/querying/clauses/_meta.json
  pages/querying/clauses/alter.mdx
  pages/querying/clauses/create.mdx
  pages/querying/clauses/load-csv.mdx
  pages/querying/differences-in-cypher-implementations.mdx
  pages/querying/functions.mdx
Labels: status: ready, future release

#876 SSO Core - OIDC + OAuth2.0 docs
  pages/database-management.md
  pages/database-management/authentication-and-authorization/auth-system-integrations.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
Labels: status: ready, future release

#871 Update v2.18 experimental feature statuses
  pages/database-management/experimental-features.mdx
Labels: status: ready, future release

#867 Add postgresql migration docs
  pages/advanced-algorithms/available-algorithms/migrate.mdx
Labels: status: ready, future release, customer

#884 Single-sign on: general and SAML documentation
  pages/data-streams.mdx
  pages/database-management.md
  pages/database-management/authentication-and-authorization/auth-system-integrations.mdx
  pages/database-management/configuration.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/fundamentals/triggers.mdx
Labels: status: ready, future release

#885 [main < 882-update-direct-download...] Update direct download paths for Memgraph 2.18
  pages/getting-started/install-memgraph/amazon-linux.mdx
  pages/getting-started/install-memgraph/centos.mdx
  pages/getting-started/install-memgraph/debian.mdx
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/getting-started/install-memgraph/fedora.mdx
  pages/getting-started/install-memgraph/redhat.mdx
  pages/getting-started/install-memgraph/rocky.mdx
  pages/getting-started/install-memgraph/ubuntu.mdx
Labels: status: ready

#770 Migration tutorial from `RDBMS` using `MAGE` modules
  pages/data-migration/_meta.json
  pages/data-migration/migrate-from-rdbms-directly.md
  pages/data-migration/migrate-from-rdbms.mdx
  public/pages/data-migration/migrate-from-rdbms-directly/migrate-from-rdbms-directly-bands-row.png
  public/pages/data-migration/migrate-from-rdbms-directly/migrate-from-rdbms-directly-connected-graph.png
  public/pages/data-migration/migrate-from-rdbms-directly/migrate-from-rdbms-directly-musicians-row.png
  public/pages/data-migration/migrate-from-rdbms-directly/migrate-from-rdbms-directly-raw-nodes.png
  public/pages/data-migration/migrate-from-rdbms-directly/migrate-from-rdbms-directly-relationships-row.png
Labels: priority: medium (missing info), status: ready, future release

#863 Add Rust query module documentation
  pages/custom-query-modules.mdx
  pages/custom-query-modules/_meta.json
  pages/custom-query-modules/cpp/cpp-api.md
  pages/custom-query-modules/cpp/cpp-example.mdx
  pages/custom-query-modules/rust/_meta.json
  pages/custom-query-modules/rust/rust-api.md
  pages/custom-query-modules/rust/rust-example.mdx
Labels: priority: high (error), status: ready, customer

#866 new: Add Lab 2.15 release notes
  pages/release-notes.mdx
Labels: status: ready, status: ship it, future release

#819 Added description how each user can change its own password
  pages/database-management/authentication-and-authorization/users.mdx
Labels: status: ready, status: ship it, future release, Docs Ready - Pending Dev Merge

#797 Add SSO docs
  pages/data-visualization/user-manual.mdx
  pages/data-visualization/user-manual/single-sign-on.mdx
  pages/database-management/ssl-encryption.mdx
  public/pages/data-visualization/lab-user-manual/sso-oidc-entra-callback.png
  public/pages/data-visualization/lab-user-manual/sso-oidc-entra-endpoints.png
  public/pages/data-visualization/lab-user-manual/sso-oidc-entra-secret.png
  public/pages/data-visualization/lab-user-manual/sso-oidc-okta-endpoints.png
  public/pages/data-visualization/lab-user-manual/sso-oidc-okta-issuer.png
  public/pages/data-visualization/lab-user-manual/sso-oidc-okta-secret.png
  public/pages/data-visualization/lab-user-manual/sso-saml-entra-app-registration.png
  public/pages/data-visualization/lab-user-manual/sso-saml-entra-copy-fields.png
  public/pages/data-visualization/lab-user-manual/sso-saml-okta-application-creation.png
  public/pages/data-visualization/lab-user-manual/sso-saml-okta-configuration.png
  public/pages/data-visualization/lab-user-manual/sso-saml-okta-copy-fields.png
Labels: Lab docs, future release

#898 SAML SSO: clarify and correct flag documentation
  pages/database-management/authentication-and-authorization/auth-system-integrations.mdx
Labels: priority: high (error), status: ready

#906 Remove zoned time as unsupported
  pages/querying/differences-in-cypher-implementations.mdx
Labels: status: ready

#919 Fix Cypher query
  pages/database-management/authentication-and-authorization/role-based-access-control.mdx
Labels: status: ship it

#923 Fix styling issues and typos
  pages/clustering/high-availability.mdx
  pages/getting-started/install-memgraph/redhat.mdx
Labels: priority: high (error), status: ship it

#888 Updated standalone helm chart config options.
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready

#809 Add `SHOW METRICS INFO` query
  pages/database-management/monitoring.mdx
  pages/database-management/server-stats.md
Labels: priority: low (improvements), status: ready, status: ship it, customer, Docs Ready - Pending Dev Merge

#808 Observe allocated deltas in system docs
  README.md
  pages/data-migration/best-practices.mdx
  pages/database-management/authentication-and-authorization/auth-system-integrations.mdx
  pages/database-management/configuration.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/database-management/monitoring.mdx
  pages/database-management/server-stats.md
  pages/fundamentals/storage-memory-usage.mdx
Labels: priority: high (error), status: ready, future release, customer

#930 [main < fix-rn-20240718] Remove release note for feature that was reverted
  pages/release-notes.mdx
Labels: status: ship it

#917 [main < 914-remove-uncompromising-docker] Update docker load instructions
  pages/getting-started/install-memgraph/docker.mdx
  public/pages/getting-started/install-memgraph/docker/7zip-step-1.png
  public/pages/getting-started/install-memgraph/docker/7zip-step-2.png
Labels: status: ready

#921 Add link from enum to alter
  pages/fundamentals/data-types.mdx
  pages/querying/clauses/alter.mdx
Labels: status: ready

#931 Added config
  pages/clustering/high-availability.mdx
Labels: future release

#916 Reloading query modules docs
  pages/custom-query-modules/manage-query-modules.mdx
Labels: status: ready, future release

#934 Better explanation of how hops limit is intended to work
  pages/advanced-algorithms/deep-path-traversal.mdx
Labels: status: ready

#932 Add user info for replication
  pages/clustering/replication.mdx
Labels: status: ready

#891 HA: Data loss -> RPO
  pages/clustering/high-availability.mdx
Labels: status: ready

#936 [main < 912-fix-unfinished-sentence] Remove empty line
  pages/getting-started/install-memgraph.mdx
Labels: status: ready

#940 [main < 895-info-about-enterprise...] Update info about enterprise license environment variables
  pages/database-management/configuration.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
Labels: status: ready

#908 Add health state and management server for coordinators
  pages/clustering/high-availability.mdx
Labels: future release

#939 [main < 938-update-direct-download-links] Update direct download links
  pages/getting-started/install-memgraph/amazon-linux.mdx
  pages/getting-started/install-memgraph/centos.mdx
  pages/getting-started/install-memgraph/debian.mdx
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/getting-started/install-memgraph/docker.mdx
  pages/getting-started/install-memgraph/fedora.mdx
  pages/getting-started/install-memgraph/redhat.mdx
  pages/getting-started/install-memgraph/rocky.mdx
  pages/getting-started/install-memgraph/ubuntu.mdx
Labels: status: ready, future release

#911 [memgraph-2-18-1 < memgraph-2-18-1-relase-notes] Release notes for Memgraph 2.18-1
  pages/release-notes.mdx
Labels: status: ready

#910 [main < memgraph-2-18-1] Memgraph 2.18.1 documentation
  README.md
  pages/clustering/high-availability.mdx
  pages/custom-query-modules/manage-query-modules.mdx
  pages/data-migration/best-practices.mdx
  pages/database-management/authentication-and-authorization/auth-system-integrations.mdx
  pages/database-management/configuration.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/database-management/monitoring.mdx
  pages/database-management/server-stats.md
  pages/fundamentals/storage-memory-usage.mdx
  pages/getting-started/install-memgraph/amazon-linux.mdx
  pages/getting-started/install-memgraph/centos.mdx
  pages/getting-started/install-memgraph/debian.mdx
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/getting-started/install-memgraph/docker.mdx
  pages/getting-started/install-memgraph/fedora.mdx
  pages/getting-started/install-memgraph/redhat.mdx
  pages/getting-started/install-memgraph/rocky.mdx
  pages/getting-started/install-memgraph/ubuntu.mdx
  pages/index.mdx
  pages/release-notes.mdx
Labels: future release

#943 [main < sitemap-update-20270724] Update sitemap
  public/sitemap.xml
Labels: status: ready, status: ship it

#928 Fix: Fix the query sharing page
  pages/data-visualization/user-manual/query-sharing.mdx
  public/pages/data-visualization/lab-user-manual/query-sharing/1_remote_storage.png
Labels: status: ready

#948 [main < 883-add-aws-gcp-azure...] Update overview page with new cloud deployment methods
  pages/deployment.mdx
Labels: status: ready
