Repository memgraph/documentation, pull requests merged in 2024-05, with the labels that each got.

#739 Update querying bp
  pages/querying/best-practices.mdx
Labels: status: ready

#736 Update graph modeling
  pages/fundamentals/graph-modeling.md
Labels: status: ready

#746 [main<] Create new page about migration from legacy version of Memgraph Platform to Memgraph MAGE
  pages/configuration/data-durability-and-backup.mdx
  pages/data-migration/_meta.json
  pages/data-migration/migrate-memgraph-platform.mdx
  public/sitemap.xml
Labels: status: draft

#723 Zoned datetime data type
  pages/advanced-algorithms/available-algorithms/date.mdx
  pages/advanced-algorithms/available-algorithms/temporal.mdx
  pages/data-migration/migrate-from-neo4j.mdx
  pages/fundamentals/data-types.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/querying/differences-in-cypher-implementations.mdx
  pages/querying/functions.mdx
Labels: status: ready, status: ship it, future release

#733 [memgraph-2.17 < ] Replicate only durable commits when in `RECOVERY`
  pages/configuration/replication.mdx
Labels: status: ready, future release

#729 [add-coord-health < ] Add elapsed time in ms
  pages/configuration/high-availability.mdx
Labels: status: ready, future release

#719 [memgraph-2.17 <] Add Bolt server to SHOW INSTANCES output
  pages/configuration/high-availability.mdx
Labels: status: ready, future release

#773 [Memgraph 2.17 < ]Update Kubernetes docs
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: priority: medium (missing info), status: ready, future release

#762 [memgraph-2.17 < ] --restore-replication-state-startup default to true
  pages/clustering/high-availability.mdx
  pages/clustering/replication.mdx
  pages/database-management/configuration.mdx
Labels: status: ready, future release

#679 Memgrpah 2.17 release notes
  pages/release-notes.mdx
Labels: status: ready, future release

#749 Add HA changes for 2.17
  pages/clustering/high-availability.mdx
Labels: status: ready, future release

#779 new: Add Lab 2.14 release notes
  pages/release-notes.mdx
Labels: status: ready

#782 [memgraph-2-17 < T782] Fix the Cypher examples for ZonedDateTime
  pages/fundamentals/data-types.mdx
Labels: priority: high (error), status: ready

#765 [memgraph-2-17 < ] Debugging memgraph
  pages/data-visualization/user-manual.mdx
  pages/database-management/_meta.json
  pages/database-management/debugging.mdx
  pages/help-center.md
  public/pages/database-management/debugging/perf.png
Labels: priority: medium (missing info), customer

#777 Improve bolt+routing section
  pages/clustering/high-availability.mdx
Labels: status: ready, future release

#728 [ha-bolt-server < ] Add coord health
  pages/clustering/high-availability.mdx
Labels: status: ready, future release

#791 Update values for Vertex
  pages/fundamentals/storage-memory-usage.mdx
Labels: future release

#680 Memgraph 2.17 docs
  pages/clustering/high-availability.mdx
  pages/clustering/replication.mdx
  pages/database-management/_meta.json
  pages/database-management/authentication-and-authorization/role-based-access-control.mdx
  pages/database-management/authentication-and-authorization/users.mdx
  pages/database-management/configuration.mdx
  pages/database-management/debugging.mdx
  pages/fundamentals/data-types.mdx
  pages/fundamentals/storage-memory-usage.mdx
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/getting-started/install-memgraph/kubernetes.mdx
  pages/help-center.md
  pages/release-notes.mdx
  public/pages/database-management/debugging/perf.png
Labels: status: ready, future release

#802 Update c-sharp driver
  pages/client-libraries/c-sharp.mdx
Labels: status: ready, status: ship it

#799 Isolation level improvements
  pages/fundamentals/transactions.mdx
Labels: priority: low (improvements), status: ready

#811 Update procedures in algo docs to include Subgraph as optional argument
  pages/advanced-algorithms/available-algorithms/algo.mdx
  pages/advanced-algorithms/available-algorithms/betweenness_centrality.mdx
  pages/advanced-algorithms/available-algorithms/betweenness_centrality_online.mdx
  pages/advanced-algorithms/available-algorithms/biconnected_components.mdx
  pages/advanced-algorithms/available-algorithms/bipartite_matching.mdx
  pages/advanced-algorithms/available-algorithms/bridges.mdx
  pages/advanced-algorithms/available-algorithms/community_detection.mdx
  pages/advanced-algorithms/available-algorithms/community_detection_online.mdx
  pages/advanced-algorithms/available-algorithms/create.mdx
  pages/advanced-algorithms/available-algorithms/cycles.mdx
  pages/advanced-algorithms/available-algorithms/degree_centrality.mdx
  pages/advanced-algorithms/available-algorithms/distance_calculator.mdx
  pages/advanced-algorithms/available-algorithms/elasticsearch_synchronization.mdx
  pages/advanced-algorithms/available-algorithms/export_util.mdx
  pages/advanced-algorithms/available-algorithms/gnn_link_prediction.mdx
  pages/advanced-algorithms/available-algorithms/gnn_node_classification.mdx
  pages/advanced-algorithms/available-algorithms/graph_analyzer.mdx
  pages/advanced-algorithms/available-algorithms/graph_coloring.mdx
  pages/advanced-algorithms/available-algorithms/graph_util.mdx
  pages/advanced-algorithms/available-algorithms/igraphalg.mdx
  pages/advanced-algorithms/available-algorithms/katz_centrality_online.mdx
  pages/advanced-algorithms/available-algorithms/kmeans_clustering.mdx
  pages/advanced-algorithms/available-algorithms/llm_util.mdx
  pages/advanced-algorithms/available-algorithms/max_flow.mdx
  pages/advanced-algorithms/available-algorithms/merge.mdx
  pages/advanced-algorithms/available-algorithms/meta_util.mdx
  pages/advanced-algorithms/available-algorithms/node.mdx
  pages/advanced-algorithms/available-algorithms/node2vec.mdx
  pages/advanced-algorithms/available-algorithms/node2vec_online.mdx
  pages/advanced-algorithms/available-algorithms/node_similarity.mdx
  pages/advanced-algorithms/available-algorithms/nodes.mdx
  pages/advanced-algorithms/available-algorithms/nxalg.mdx
  pages/advanced-algorithms/available-algorithms/pagerank.mdx
  pages/advanced-algorithms/available-algorithms/pagerank_online.mdx
  pages/advanced-algorithms/available-algorithms/path.mdx
  pages/advanced-algorithms/available-algorithms/refactor.mdx
  pages/advanced-algorithms/available-algorithms/set_cover.mdx
  pages/advanced-algorithms/available-algorithms/set_property.mdx
  pages/advanced-algorithms/available-algorithms/tgn.mdx
  pages/advanced-algorithms/available-algorithms/tsp.mdx
  pages/advanced-algorithms/available-algorithms/union_find.mdx
  pages/advanced-algorithms/available-algorithms/uuid_generator.mdx
  pages/advanced-algorithms/available-algorithms/vrp.mdx
  pages/advanced-algorithms/available-algorithms/weakly_connected_components.mdx
  pages/advanced-algorithms/available-algorithms/xml_module.mdx
  pages/advanced-algorithms/run-algorithms.mdx
Labels: status: ready
