Repository memgraph/documentation, pull requests merged in 2024-06, with the labels that each got.

#825 Add coming soon page
  components/input-form/InputForm.tsx
  pages/coming-soon.mdx
  styles/globals.css
Labels: status: ready, status: ship it

#816 Add NuRaft logs
  pages/clustering/high-availability.mdx
  pages/database-management/configuration.mdx
Labels: status: ready, status: ship it, future release

#827 Change coming soon form
  components/input-form/InputForm.tsx
Labels: status: ready

#836 Create overview page for Deployment practices
  pages/deployment.mdx
Labels: status: ship it

#833 Add health checks docs
  pages/clustering/high-availability.mdx
  pages/database-management/configuration.mdx
Labels: status: ready, future release

#828 Improve high availability docs
  pages/clustering/high-availability.mdx
  pages/database-management/configuration.mdx
Labels: status: ready

#807 Memgraph vs. Adya weak consistency
  pages/fundamentals/transactions.mdx
Labels: status: ready

#839 [main < supported-linux-distributions] Add a note about supported Linux distributions
  pages/getting-started/install-memgraph/direct-download-links.mdx
Labels: status: ready, status: ship it

#832 Create a new page about experimental features
  pages/clustering/replication/experimental-replication.mdx
  pages/database-management/_meta.json
  pages/database-management/configuration.mdx
  pages/database-management/experimental-features.mdx
  pages/querying/text-search.mdx
Labels: status: ready

#843 HA improvements
  pages/clustering/high-availability.mdx
Labels: status: ready, status: ship it

#842 [main < typo-fix-20240614] Fix typos
  pages/advanced-algorithms/available-algorithms/bipartite_matching.mdx
  pages/advanced-algorithms/available-algorithms/bridges.mdx
  pages/advanced-algorithms/available-algorithms/collections.mdx
  pages/advanced-algorithms/available-algorithms/create.mdx
  pages/advanced-algorithms/available-algorithms/export_util.mdx
  pages/advanced-algorithms/available-algorithms/igraphalg.mdx
  pages/advanced-algorithms/available-algorithms/neighbors.mdx
  pages/advanced-algorithms/available-algorithms/node2vec.mdx
  pages/advanced-algorithms/available-algorithms/nxalg.mdx
  pages/advanced-algorithms/available-algorithms/path.mdx
  pages/client-libraries/go.mdx
  pages/client-libraries/java.mdx
  pages/client-libraries/python.mdx
  pages/client-libraries/rust.mdx
  pages/custom-query-modules/cpp/cpp-example.mdx
  pages/data-migration/best-practices.mdx
  pages/data-migration/migrate-from-neo4j.mdx
  pages/data-streams/kafka.mdx
  pages/data-streams/transformation-modules/python-api.mdx
  pages/data-visualization/graph-style-script.md
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/fundamentals/transactions.mdx
  pages/fundamentals/triggers.mdx
  pages/querying/differences-in-cypher-implementations.mdx
  pages/querying/exploring-datasets/analyzing-ted-talks.md
  pages/querying/schema.mdx
  pages/release-notes.mdx
Labels: status: ready

#844 HA improvements
  pages/clustering/high-availability.mdx
Labels: status: ready

#847 Add docker compose example for running HA
  pages/clustering/high-availability.mdx
Labels: status: ready

#849 Update Lab env
  pages/data-visualization/install-and-connect.mdx
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ship it

#857 Add leader/follower role
  pages/clustering/high-availability.mdx
Labels: status: ready, future release, Docs Ready - Pending Dev Merge

#856 [main < 713-document-an-request-limit-error] Add request limit notice
  pages/data-visualization/user-manual.mdx
Labels: status: ready

#862 [mail < daily-fix-20240624] Fix command DENY ALL PRIVILEGES TO
  pages/database-management/authentication-and-authorization/role-based-access-control.mdx
Labels: status: ship it

#858 Add custom bridge network in docker compose
  pages/clustering/high-availability.mdx
Labels: status: ready, future release

#860 Add coordinator hostname HA configuration option
  pages/clustering/high-availability.mdx
  pages/database-management/configuration.mdx
Labels: status: ready, future release

#806 Add monitoring at runtime docs
  pages/database-management/monitoring.mdx
Labels: priority: high (error), status: ready, status: ship it, future release, customer, Docs Ready - Pending Dev Merge

#861 Update import bp
  pages/data-migration/best-practices.mdx
Labels: status: ship it

#853 Database-less connections
  pages/database-management/multi-tenancy.md
Labels: future release, Docs Ready - Pending Dev Merge

#870 Document `SHOW CURRENT USER`
  pages/database-management/authentication-and-authorization/users.mdx
Labels: priority: medium (missing info), status: ready, memgraph-2-18

#859 Add durability for coordinator
  pages/clustering/high-availability.mdx
  pages/database-management/configuration.mdx
Labels: status: ready, future release

#841 [main < 840-update-direct...] Update the name of Docker image file
  pages/getting-started/install-memgraph/docker.mdx
  public/pages/getting-started/install-memgraph/docker/7zip-step-1.png
  public/pages/getting-started/install-memgraph/docker/7zip-step-2.png
Labels: status: ready

#855 Edge type property index
  pages/fundamentals/indexes.mdx
Labels: status: ready, future release, Docs Ready - Pending Dev Merge

#880 [main < 879-update-sitemap] Update sitemap
  public/sitemap.xml
Labels: priority: low (improvements)
