Repository memgraph/documentation, pull requests merged in 2025-10, with the labels that each got.

#1408 feat: Add optional service monitor to HA chart
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, customer, feature

#1419 User-role mapping clarification
  pages/database-management/authentication-and-authorization/multiple-roles.mdx
  pages/database-management/authentication-and-authorization/role-based-access-control.mdx
  pages/database-management/multi-tenancy.md
Labels: status: ready, bugfix

#1418 New features: Rename and Force drop database
  next-env.d.ts
  pages/database-management/multi-tenancy.mdx
Labels: status: ready, feature

#1421 Set nested properties documentation
  pages/deployment/workloads/memgraph-in-cybersecurity.mdx
  pages/querying/clauses/set.md
  pages/querying/read-and-modify-data.md
Labels: priority: low (improvements), status: ready, customer, feature

#1422 Add text edge index, relevance score and limit parameters to text search docs
  pages/querying/text-search.mdx
Labels: feature

#1425 Filter with pattern expressions documentation
  pages/querying/clauses/where.md
  pages/querying/differences-in-cypher-implementations.mdx
Labels: priority: low (improvements), customer, feature

#1427 Fix deny/revoke database query
  pages/database-management/authentication-and-authorization/multiple-roles.mdx
  pages/database-management/multi-tenancy.mdx
Labels: status: ready, bugfix
