Repository memgraph/documentation, pull requests merged in 2025-09, with the labels that each got.

#1388 Add Lab data modeling page
  components/release-notes/LabReleasesClient.js
  pages/memgraph-lab/features.mdx
  pages/memgraph-lab/features/_meta.ts
  pages/memgraph-lab/features/data-modeling.mdx
  public/pages/data-visualization/features/data-modeling/data-modeling.png
Labels: status: ready, Lab docs, feature

#1399 Update the migration module guide
  pages/data-migration/migrate-from-neo4j-using-single-cypher-query.mdx
Labels: priority: medium (missing info)

#1407 feat: Add optional init containers to HA chart
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, feature

#1404 feat: Support MT authentication with bolt+routing on the HA cluster
  pages/clustering/high-availability.mdx
Labels: feature

#1389 feat: Add ISSU docs
  pages/clustering/high-availability.mdx
Labels: status: ready, feature

#1410 feat: lifecycleHooks and volumes in the standalone chart
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, customer, feature

#1417 Update vm.max_map_count info
  pages/database-management/system-configuration.mdx
  pages/deployment/workloads/memgraph-in-high-throughput-workloads.mdx
Labels: priority: medium (missing info)
