Repository memgraph/documentation, pull requests merged in 2025-06, with the labels that each got.

#1287 new: Add query sharing with params
  pages/memgraph-lab/configuration.mdx
  pages/memgraph-lab/features/sharing-features.mdx
  public/pages/data-visualization/lab-user-manual/query-sharing/2_sharequery_1.png
  public/pages/data-visualization/lab-user-manual/query-sharing/3_sharequery_2.png
  public/pages/data-visualization/lab-user-manual/query-sharing/4_sharequery_3.png
  public/pages/data-visualization/lab-user-manual/query-sharing/query-share-configuration.png
  public/pages/data-visualization/lab-user-manual/query-sharing/query-share-query-setup.png
  public/pages/data-visualization/lab-user-manual/query-sharing/query-share-template-params.png
  public/pages/data-visualization/lab-user-manual/query-sharing/query-share-template-query.png
  public/pages/data-visualization/lab-user-manual/query-sharing/query-share-url-params.png
  public/pages/data-visualization/lab-user-manual/query-sharing/query-share-url.png
Labels: Lab docs, future release

#1274 Document failovering to sync replicas only
  pages/clustering/high-availability.mdx
Labels: status: ready, feature

#1281 Update on HA timeouts
  pages/clustering/high-availability.mdx
  pages/release-notes.mdx
Labels: status: ready, feature

#1275 Add monitoring through Prometheus for HA chart
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, feature

#1302 Scheduler docs
  pages/database-management/configuration.mdx
Labels: status: ready, feature

#1300 Add how to debug GDB under MG charts
  pages/database-management/debugging.mdx
Labels: priority: low (improvements), status: ready

#1297 Nested indices
  pages/fundamentals/indexes.mdx
Labels: feature

#1271 Add docs for enabled reads on main
  pages/clustering/high-availability.mdx
Labels: status: ready, feature

#1273 Improve failure mode, add multiple DCs
  pages/clustering/high-availability.mdx
Labels: priority: low (improvements), status: ready

#1313 Add scalar_kind options to vector index
  pages/querying/vector-search.mdx
Labels: feature
