Repository memgraph/documentation, pull requests merged in 2025-03, with the labels that each got.

#1130 Add RPC timeouts for SystemHeartbeatReq, SystemRecoveryReq and ForceResetStorageReq
  pages/clustering/high-availability.mdx
Labels: feature

#1142 Add TCP probes to HA chart and standalone chart
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: feature

#1126 Added mgp_list_reserve and List::Reserve
  pages/custom-query-modules/c/c-api.mdx
  pages/custom-query-modules/cpp/cpp-api.md
Labels: feature

#1143 Optionally create storage class in the standalone chart
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: bugfix

#1146 Length function not difference
  pages/querying/differences-in-cypher-implementations.mdx
Labels: priority: high (error)

#1149 Add RPC timeouts for AppendDeltasRPC, CurrentWalRPC, WalFilesRPC and SnapshotRPC
  pages/clustering/high-availability.mdx
Labels: status: ready, feature

#1157 Migrate from S3
  pages/advanced-algorithms/available-algorithms/migrate.mdx
  pages/data-migration.mdx
Labels: status: ready, customer, feature

#1159 Add `toSet()` function
  pages/querying/functions.mdx
Labels: customer, feature

#1169 Remove options for specifying protocol
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, feature

#1170 Bugfix: Unregister replication instance could lead to a deadlock
  pages/clustering/high-availability.mdx
Labels: status: ready, bugfix

#1171 Show vector index info
  pages/fundamentals/indexes.mdx
  pages/querying/vector-search.mdx
Labels: status: ready, feature

#1174 Bugfix: force reset causes data loss and deletion of durability files in HA environment
  pages/clustering/high-availability.mdx
Labels: bugfix

#1178 Update community detection docs
  pages/advanced-algorithms/available-algorithms/community_detection.mdx
Labels: feature

#1156 Dynamic node labels within list
  pages/querying/expressions.mdx
Labels: status: ready, customer, feature

#1179 Impersonate user
  pages/client-libraries/python.mdx
  pages/database-management/authentication-and-authorization.mdx
  pages/database-management/authentication-and-authorization/_meta.ts
  pages/database-management/authentication-and-authorization/impersonate-user.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
Labels: status: ready, feature

#1180 Query resources and storage access timeout
  pages/help-center/errors/transactions.mdx
Labels: status: ready, bugfix

#1187 Add --debug-query-plans
  pages/database-management/configuration.mdx
  pages/database-management/logs.mdx
  pages/querying/best-practices.mdx
Labels: feature

#1185 tzdata version incompatibility warning
  pages/advanced-algorithms/available-algorithms/date.mdx
  pages/fundamentals/data-types.mdx
Labels: status: ready, bugfix

#1125 Memgraph 3.1
  next-env.d.ts
  pages/advanced-algorithms/available-algorithms/community_detection.mdx
  pages/advanced-algorithms/available-algorithms/date.mdx
  pages/advanced-algorithms/available-algorithms/migrate.mdx
  pages/advanced-algorithms/available-algorithms/pagerank.mdx
  pages/client-libraries/python.mdx
  pages/clustering/high-availability.mdx
  pages/custom-query-modules/c/c-api.mdx
  pages/custom-query-modules/cpp/cpp-api.md
  pages/data-migration.mdx
  pages/data-migration/csv.mdx
  pages/database-management/authentication-and-authorization.mdx
  pages/database-management/authentication-and-authorization/_meta.ts
  pages/database-management/authentication-and-authorization/auth-system-integrations.mdx
  pages/database-management/authentication-and-authorization/impersonate-user.mdx
  pages/database-management/configuration.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/database-management/logs.mdx
  pages/fundamentals/data-types.mdx
  pages/fundamentals/indexes.mdx
  pages/getting-started/install-memgraph/kubernetes.mdx
  pages/help-center/errors/transactions.mdx
  pages/querying/best-practices.mdx
  pages/querying/clauses/create.mdx
  pages/querying/differences-in-cypher-implementations.mdx
  pages/querying/expressions.mdx
  pages/querying/functions.mdx
  pages/querying/vector-search.mdx
  pages/release-notes.mdx
Labels: release

#1088 Update toolchain-v6
  pages/getting-started/build-memgraph-from-source.mdx
Labels: infrastructure

#1191 added missing link to Fedora toolchain
  pages/getting-started/build-memgraph-from-source.mdx
Labels: bugfix

#1198 Patch release for Helm Charts HA
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, bugfix

#1202 Explicitly use quotes in the RECOVER SNAPSHOT query
  pages/database-management/backup-and-restore.mdx
Labels: status: ready

#1136 Dynamic release notes rendering
  components/release-notes/LabReleasesClient.js
  pages/release-notes.mdx
  utils/fetchData.js
Labels: priority: low (improvements), status: ready

#1201 Update Langchain integration docs
  pages/ai-ecosystem/integrations.mdx
Labels: feature

#1145 Add list comprehension
  pages/querying/differences-in-cypher-implementations.mdx
  pages/querying/expressions.mdx
  pages/release-notes.mdx
Labels: customer

#1208 Update MAGE installation Instructions
  pages/advanced-algorithms.mdx
  pages/advanced-algorithms/install-mage.mdx
  pages/getting-started/install-memgraph/docker.mdx
Labels: feature

#1200 Add HA docs, common issues and split brain explanation
  pages/clustering/high-availability.mdx
  pages/getting-started/install-memgraph/kubernetes.mdx
  pages/help-center/errors/_meta.ts
  pages/help-center/errors/high-availability.mdx
Labels: priority: low (improvements), status: ready

#1195 Fix missing query modules documentation
  next.config.mjs
  pages/advanced-algorithms/available-algorithms.mdx
  pages/advanced-algorithms/available-algorithms/_meta.ts
  pages/advanced-algorithms/available-algorithms/csv_utils.mdx
  pages/advanced-algorithms/available-algorithms/do.mdx
  pages/advanced-algorithms/available-algorithms/graph_analyzer.mdx
  pages/advanced-algorithms/available-algorithms/meta.mdx
  pages/advanced-algorithms/available-algorithms/tgn.mdx
  pages/release-notes.mdx
  public/pages/advanced-algorithms/available-algorithms/do/do-1.png
Labels: status: ready, feature

#1203 Add migration module from Neo4j
  pages/advanced-algorithms/available-algorithms/migrate.mdx
  pages/data-migration.mdx
Labels: feature

#1210 Added new instructions for building using docker hub images
  pages/custom-query-modules.mdx
Labels: feature

#1199 Memgraph 3.1.1
  pages/advanced-algorithms.mdx
  pages/advanced-algorithms/available-algorithms/migrate.mdx
  pages/advanced-algorithms/install-mage.mdx
  pages/custom-query-modules.mdx
  pages/data-migration.mdx
  pages/database-management/backup-and-restore.mdx
  pages/getting-started/install-memgraph/docker.mdx
  pages/querying/differences-in-cypher-implementations.mdx
  pages/querying/expressions.mdx
  pages/release-notes.mdx
Labels: release
