Repository memgraph/documentation, pull requests merged in 2025-01, with the labels that each got.

#1089 Add Cypher `toStringOfNull` function
  pages/querying/functions.mdx
Labels: feature

#1099 Add RPC timeouts
  pages/clustering/high-availability.mdx
Labels: feature

#1085 Add dynamic relationship creation
  pages/data-migration/csv.mdx
  pages/querying/clauses/create.mdx
Labels: customer, feature

#1083 Add `SHOW LICENSE INFO` query
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/database-management/server-stats.md
Labels: status: ready, feature

#1100 Improve HA durability docs
  pages/clustering/high-availability.mdx
  pages/database-management/configuration.mdx
Labels: bugfix

#1103 Remove warning
  pages/fundamentals/indexes.mdx
Labels: bugfix

#1005 Add vector search
  pages/database-management/configuration.mdx
  pages/database-management/experimental-features.mdx
  pages/querying/vector-search.mdx
Labels: status: ready, feature

#1106 Update docs for security context
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: priority: medium (missing info), bugfix

#1105 new: Add Lab 3.0.0 release notes
  pages/data-visualization/user-manual/graph-style-script-sharing.mdx
  pages/data-visualization/user-manual/query-sharing.mdx
  pages/data-visualization/user-manual/remote-storage.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/release-notes.mdx
Labels: status: ready, feature

#1113 Wrong information for HA docker compose setup
  pages/clustering/high-availability.mdx
Labels: priority: high (error), status: ready

#1116 Remove IngressNginx specific configuration
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: feature

#1119 Mention text and vector search under index page
  pages/fundamentals/indexes.mdx
Labels: status: ready, bugfix

#1117 Dynamic algos updates
  next.config.mjs
  pages/advanced-algorithms.mdx
  pages/advanced-algorithms/available-algorithms.mdx
  pages/advanced-algorithms/available-algorithms/betweenness_centrality_online.mdx
  pages/advanced-algorithms/available-algorithms/community_detection_online.mdx
  pages/advanced-algorithms/available-algorithms/katz_centrality_online.mdx
  pages/advanced-algorithms/available-algorithms/node2vec_online.mdx
  pages/advanced-algorithms/available-algorithms/pagerank_online.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/fundamentals/triggers.mdx
Labels: feature

#1121 docs: Add signature for two-argument version of `collect()`
  pages/querying/functions.mdx
Labels: feature

#1122 new: Add new lines for the Lab 3.0 release notes
  pages/release-notes.mdx
Labels: status: ready, Lab docs

#1084 Memgraph 3.0 release
  next.config.mjs
  pages/advanced-algorithms.mdx
  pages/advanced-algorithms/available-algorithms.mdx
  pages/advanced-algorithms/available-algorithms/betweenness_centrality_online.mdx
  pages/advanced-algorithms/available-algorithms/community_detection_online.mdx
  pages/advanced-algorithms/available-algorithms/katz_centrality_online.mdx
  pages/advanced-algorithms/available-algorithms/node2vec_online.mdx
  pages/advanced-algorithms/available-algorithms/pagerank_online.mdx
  pages/clustering/high-availability.mdx
  pages/custom-query-modules/cpp/cpp-api.md
  pages/data-visualization/user-manual/graph-style-script-sharing.mdx
  pages/data-visualization/user-manual/query-sharing.mdx
  pages/data-visualization/user-manual/remote-storage.mdx
  pages/database-management/configuration.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/database-management/experimental-features.mdx
  pages/database-management/server-stats.md
  pages/fundamentals/indexes.mdx
  pages/fundamentals/triggers.mdx
  pages/getting-started/install-memgraph/amazon-linux.mdx
  pages/getting-started/install-memgraph/centos.mdx
  pages/getting-started/install-memgraph/debian.mdx
  pages/getting-started/install-memgraph/direct-download-links.mdx
  pages/getting-started/install-memgraph/docker.mdx
  pages/getting-started/install-memgraph/fedora.mdx
  pages/getting-started/install-memgraph/kubernetes.mdx
  pages/getting-started/install-memgraph/redhat.mdx
  pages/getting-started/install-memgraph/rocky.mdx
  pages/getting-started/install-memgraph/ubuntu.mdx
  pages/querying/differences-in-cypher-implementations.mdx
  pages/querying/functions.mdx
  pages/querying/vector-search.mdx
  pages/release-notes.mdx
Labels: release

#1128 new: Add Lab 3.0.1 changelog
  pages/release-notes.mdx
Labels: status: ready, Lab docs
