Repository memgraph/documentation, pull requests merged in 2025-08, with the labels that each got.

#1365 Add labels support for HA chart
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, feature

#1371 Auto-index and TTL
  pages/fundamentals/indexes.mdx
  pages/querying/time-to-live.mdx
Labels: feature

#1373 Add docs for SSO changes
  pages/client-libraries/python.mdx
  pages/database-management/authentication-and-authorization/auth-system-integrations.mdx
Labels: feature

#1374 Added Apoc mappings able and described new functions added: toTree, fromJsonList, toJson, flatten and indexOf
  next-env.d.ts
  pages/advanced-algorithms/available-algorithms.mdx
  pages/advanced-algorithms/available-algorithms/_meta.ts
  pages/advanced-algorithms/available-algorithms/collections.mdx
  pages/advanced-algorithms/available-algorithms/convert.mdx
  pages/advanced-algorithms/available-algorithms/convert_c.mdx
  pages/advanced-algorithms/available-algorithms/create.mdx
  pages/advanced-algorithms/available-algorithms/date.mdx
  pages/advanced-algorithms/available-algorithms/json_util.mdx
  pages/advanced-algorithms/available-algorithms/label.mdx
  pages/advanced-algorithms/available-algorithms/map.mdx
  pages/advanced-algorithms/available-algorithms/mgps.mdx
  pages/advanced-algorithms/available-algorithms/refactor.mdx
  pages/advanced-algorithms/available-algorithms/text.mdx
  pages/advanced-algorithms/available-algorithms/util_module.mdx
  pages/deployment/workloads/memgraph-in-cybersecurity.mdx
  pages/deployment/workloads/memgraph-in-high-throughput-workloads.mdx
  pages/help-center/faq.mdx
  pages/querying/functions.mdx
Labels: status: ready, customer, feature

#1345 User profiles
  pages/database-management/authentication-and-authorization.mdx
  pages/database-management/authentication-and-authorization/_meta.ts
  pages/database-management/authentication-and-authorization/role-based-access-control.mdx
  pages/database-management/authentication-and-authorization/user-profiles.mdx
  pages/database-management/authentication-and-authorization/users.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
Labels: status: ready, feature

#1358 Existential subqueries
  pages/querying/clauses/where.md
  pages/querying/differences-in-cypher-implementations.mdx
  pages/querying/expressions.mdx
Labels: priority: low (improvements), status: ready, customer, feature

#1337 Multi-role user with ability to link roles to specific databases
  pages/clustering/replication.mdx
  pages/database-management/authentication-and-authorization.mdx
  pages/database-management/authentication-and-authorization/_meta.ts
  pages/database-management/authentication-and-authorization/auth-system-integrations.mdx
  pages/database-management/authentication-and-authorization/multiple-roles.mdx
  pages/database-management/authentication-and-authorization/role-based-access-control.mdx
  pages/database-management/authentication-and-authorization/users.mdx
  pages/database-management/enabling-memgraph-enterprise.mdx
  pages/database-management/multi-tenancy.md
  pages/help-center/errors/auth.mdx
Labels: status: ready, feature

#1359 Add database UUID to show storage info
  pages/database-management/backup-and-restore.mdx
  pages/database-management/multi-tenancy.md
  pages/database-management/server-stats.md
  pages/fundamentals/storage-memory-usage.mdx
Labels: priority: low (improvements), status: ready, customer, feature

#1364 Overload show methods for indexes, constraints, vector indexes, triggers, active users
  pages/database-management/server-stats.md
  pages/fundamentals/constraints.mdx
  pages/fundamentals/indexes.mdx
  pages/fundamentals/triggers.mdx
Labels: priority: low (improvements), status: ready, feature

#1372 Add API reference for ZonedDateTime
  pages/custom-query-modules/c/c-api.mdx
  pages/custom-query-modules/cpp/cpp-api.md
Labels: feature
