Repository memgraph/documentation, pull requests merged in 2025-04, with the labels that each got.

#1221 Add section about coordinator deployment in HA
  pages/clustering/high-availability.mdx
Labels: priority: low (improvements), status: ready

#1234 HA MT failover
  pages/clustering/high-availability.mdx
Labels: status: ready, feature

#1236 Add mgp_result_reserve to C-API
  pages/custom-query-modules/c/c-api.mdx
Labels: feature

#1231 Add a section about manual failover in HA
  pages/clustering/high-availability.mdx
Labels: priority: low (improvements), status: ready, feature

#1241 Add headless service option on HA chart
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: feature

#1240 Add docs for OR label expressions
  pages/querying/clauses/match.mdx
  pages/querying/differences-in-cypher-implementations.mdx
  public/pages/querying/clauses/graph_schema.png
Labels: feature

#1232 Add composite indices
  pages/database-management/monitoring.mdx
  pages/database-management/server-stats.md
  pages/fundamentals/indexes.mdx
  pages/querying/best-practices.mdx
  pages/querying/differences-in-cypher-implementations.mdx
  pages/querying/query-plan.mdx
  pages/querying/schema.mdx
Labels: feature

#1243 Create snapshot parallelization
  pages/database-management/configuration.mdx
  pages/fundamentals/data-durability.mdx
  pages/help-center/errors/snapshots.mdx
Labels: status: ready, feature

#1248 Add annotations support for external access services in HA chart
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, feature

#1249 Add support for service labels in standalone chart
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, feature

#1207 Add migration from ServiceNow
  pages/advanced-algorithms/available-algorithms/migrate.mdx
Labels: customer, feature

#1206 Add migration from another Memgraph instance
  pages/advanced-algorithms/available-algorithms/migrate.mdx
Labels: customer, feature

#1205 Add migration module with DuckDB
  pages/advanced-algorithms/available-algorithms/migrate.mdx
Labels: customer, feature

#1204 Add migration module with Arrow Flight
  pages/advanced-algorithms/available-algorithms/migrate.mdx
Labels: customer, feature

#1250 Add support for starting HA chart without external network configuration
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, feature

#1237 Update storage access types
  pages/client-libraries/python.mdx
  pages/fundamentals/_meta.ts
  pages/fundamentals/storage-access.mdx
  pages/help-center/errors/transactions.mdx
Labels: status: ready, feature

#1253 Global edge index documentation
  pages/fundamentals/indexes.mdx
Labels: feature

#1263 Evaluating memgraph
  pages/memgraph-in-production.mdx
  pages/memgraph-in-production/_meta.ts
  pages/memgraph-in-production/benchmarking-memgraph.mdx
  public/pages/memgraph-in-production/benchmarking-memgraph/benchgraph-snippet.png
Labels: priority: medium (missing info)

#1239 Memgraph in production guides (general and GraphRAG)
  pages/_meta.ts
  pages/fundamentals/storage-memory-usage.mdx
  pages/getting-started/install-memgraph.mdx
  pages/memgraph-in-production.mdx
  pages/memgraph-in-production/_meta.ts
  pages/memgraph-in-production/benchmarking-memgraph.mdx
  pages/memgraph-in-production/general-suggestions.mdx
  pages/memgraph-in-production/memgraph-in-graphrag.mdx
  public/pages/memgraph-in-production/benchmarking-memgraph/benchgraph-snippet.png
Labels: priority: low (improvements)

#1260 Add support for Prometheus on HA Helm charts
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, customer, feature

#1264 Add storage per instances on HA chart
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, customer, feature

#1266 Memgraph in high throughput workloads
  pages/_meta.ts
  pages/memgraph-in-production.mdx
  pages/memgraph-in-production/_meta.ts
  pages/memgraph-in-production/general-suggestions.mdx
  pages/memgraph-in-production/memgraph-in-high-throughput-workloads.mdx
  public/pages/memgraph-in-production/benchmarking-memgraph/realistic-workload.png
Labels: priority: medium (missing info)

#1247 Add resources to HA chart
  pages/getting-started/install-memgraph/kubernetes.mdx
Labels: status: ready, customer, feature

#1257 Add restore snapshot better explanation
  pages/database-management/backup-and-restore.mdx
Labels: priority: medium (missing info)

#1262 Updated go, java, js drivers
  pages/client-libraries/go.mdx
  pages/client-libraries/java.mdx
  pages/client-libraries/javascript.mdx
  pages/client-libraries/nodejs.mdx
Labels: priority: medium (missing info), status: ready
